#!/bin/bash

set -ex
server_type=${1}

DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}"

goose -dir /app/migrations postgres "${DATABASE_URL}" up
case "${server_type}" in
  "worker")
    gecko workers
    ;;
  "web")
    gecko serve
    ;;
  *)
    echo "Invalid server type: ${server_type}"
    exit 1
    ;;
esac
