// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const apiKeyCreate = `-- name: ApiKeyCreate :one
INSERT INTO api_keys (tenant_id, user_id, name, prefix, key_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uid, tenant_id, user_id, name, prefix, key_hash, last_used_at, expires_at, revoked_at, created_at
`

type ApiKeyCreateParams struct {
	TenantID  int32              `json:"tenant_id"`
	UserID    int32              `json:"user_id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	KeyHash   string             `json:"key_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) ApiKeyCreate(ctx context.Context, arg ApiKeyCreateParams) (ApiKeys, error) {
	row := q.db.QueryRow(ctx, apiKeyCreate,
		arg.TenantID,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.KeyHash,
		arg.ExpiresAt,
	)
	var i ApiKeys
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const apiKeyGetByPrefix = `-- name: ApiKeyGetByPrefix :one
SELECT k.id,
       k.uid,
       k.tenant_id,
       k.user_id,
       k.name,
       k.prefix,
       k.key_hash,
       k.last_used_at,
       k.expires_at,
       k.revoked_at,
       k.created_at,
       u.email  AS user_email,
       m.role   AS user_role,
       u.status AS user_status
FROM api_keys k
         JOIN users u ON u.id = k.user_id
         JOIN memberships m ON m.user_id = k.user_id AND m.tenant_id = k.tenant_id
WHERE k.prefix = $1
`

type ApiKeyGetByPrefixRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	TenantID   int32              `json:"tenant_id"`
	UserID     int32              `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	KeyHash    string             `json:"key_hash"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UserEmail  string             `json:"user_email"`
	UserRole   UserRole           `json:"user_role"`
	UserStatus UserStatus         `json:"user_status"`
}

// Returns the key plus the owner's status and per-tenant role so verification can
// reject keys belonging to non-active users in a single round-trip. The INNER JOIN
// on memberships sources the role for the key's tenant and is load-bearing: if the
// user's membership in that tenant was revoked, the row vanishes and the key is
// rejected, so a key cannot outlive the membership it was scoped to.
func (q *Queries) ApiKeyGetByPrefix(ctx context.Context, prefix string) (ApiKeyGetByPrefixRow, error) {
	row := q.db.QueryRow(ctx, apiKeyGetByPrefix, prefix)
	var i ApiKeyGetByPrefixRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UserEmail,
		&i.UserRole,
		&i.UserStatus,
	)
	return i, err
}

const apiKeyRevoke = `-- name: ApiKeyRevoke :one
UPDATE api_keys
SET revoked_at = NOW()
WHERE uid = $1
  AND tenant_id = $2
  AND revoked_at IS NULL
RETURNING id, uid, tenant_id, user_id, name, prefix, created_at
`

type ApiKeyRevokeParams struct {
	Uid      string `json:"uid"`
	TenantID int32  `json:"tenant_id"`
}

type ApiKeyRevokeRow struct {
	ID        int32              `json:"id"`
	Uid       string             `json:"uid"`
	TenantID  int32              `json:"tenant_id"`
	UserID    int32              `json:"user_id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ApiKeyRevoke(ctx context.Context, arg ApiKeyRevokeParams) (ApiKeyRevokeRow, error) {
	row := q.db.QueryRow(ctx, apiKeyRevoke, arg.Uid, arg.TenantID)
	var i ApiKeyRevokeRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.CreatedAt,
	)
	return i, err
}

const apiKeyTouchLastUsed = `-- name: ApiKeyTouchLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) ApiKeyTouchLastUsed(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, apiKeyTouchLastUsed, id)
	return err
}

const apiKeysListByTenant = `-- name: ApiKeysListByTenant :many
SELECT id, uid, tenant_id, user_id, name, prefix, last_used_at, expires_at, revoked_at, created_at
FROM api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ApiKeysListByTenantRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	TenantID   int32              `json:"tenant_id"`
	UserID     int32              `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ApiKeysListByTenant(ctx context.Context, tenantID int32) ([]ApiKeysListByTenantRow, error) {
	rows, err := q.db.Query(ctx, apiKeysListByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeysListByTenantRow{}
	for rows.Next() {
		var i ApiKeysListByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const apiKeysListByUser = `-- name: ApiKeysListByUser :many
SELECT id, uid, tenant_id, user_id, name, prefix, last_used_at, expires_at, revoked_at, created_at
FROM api_keys
WHERE tenant_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type ApiKeysListByUserParams struct {
	TenantID int32 `json:"tenant_id"`
	UserID   int32 `json:"user_id"`
}

type ApiKeysListByUserRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	TenantID   int32              `json:"tenant_id"`
	UserID     int32              `json:"user_id"`
	Name       string             `json:"name"`
	Prefix     string             `json:"prefix"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ApiKeysListByUser(ctx context.Context, arg ApiKeysListByUserParams) ([]ApiKeysListByUserRow, error) {
	rows, err := q.db.Query(ctx, apiKeysListByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeysListByUserRow{}
	for rows.Next() {
		var i ApiKeysListByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
