// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assessors.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assessCreateCAAComplianceFinding = `-- name: AssessCreateCAAComplianceFinding :one
INSERT INTO caa_compliance_findings (domain_id,
                                     caa_record_id,
                                     severity,
                                     status,
                                     issue_type,
                                     standard_name,
                                     details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (domain_id, issue_type)
    DO UPDATE SET caa_record_id = $2,
                  severity      = $3,
                  status        = $4,
                  standard_name = $6,
                  details       = $7
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateCAAComplianceFindingParams struct {
	DomainID     pgtype.Int4     `json:"domain_id"`
	CaaRecordID  pgtype.Int4     `json:"caa_record_id"`
	Severity     FindingSeverity `json:"severity"`
	Status       FindingStatus   `json:"status"`
	IssueType    string          `json:"issue_type"`
	StandardName pgtype.Text     `json:"standard_name"`
	Details      pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateCAAComplianceFinding(ctx context.Context, arg AssessCreateCAAComplianceFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateCAAComplianceFinding,
		arg.DomainID,
		arg.CaaRecordID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.StandardName,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateCAAConfigurationFinding = `-- name: AssessCreateCAAConfigurationFinding :one
INSERT INTO caa_configuration_findings (domain_id,
                                        caa_record_id,
                                        severity,
                                        status,
                                        issue_type,
                                        details)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (domain_id, issue_type)
    DO UPDATE SET caa_record_id = $2,
                  severity      = $3,
                  status        = $4,
                  details       = $6
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateCAAConfigurationFindingParams struct {
	DomainID    pgtype.Int4     `json:"domain_id"`
	CaaRecordID pgtype.Int4     `json:"caa_record_id"`
	Severity    FindingSeverity `json:"severity"`
	Status      FindingStatus   `json:"status"`
	IssueType   string          `json:"issue_type"`
	Details     pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateCAAConfigurationFinding(ctx context.Context, arg AssessCreateCAAConfigurationFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateCAAConfigurationFinding,
		arg.DomainID,
		arg.CaaRecordID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateCertificateFinding = `-- name: AssessCreateCertificateFinding :one
INSERT INTO certificate_findings (domain_id,
                                  certificate_id,
                                  severity,
                                  status,
                                  issue_type,
                                  details)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (domain_id, issue_type)
    DO UPDATE SET certificate_id = $2,
                  severity       = $3,
                  status         = $4,
                  details        = $6
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateCertificateFindingParams struct {
	DomainID      pgtype.Int4     `json:"domain_id"`
	CertificateID pgtype.Int4     `json:"certificate_id"`
	Severity      FindingSeverity `json:"severity"`
	Status        FindingStatus   `json:"status"`
	IssueType     string          `json:"issue_type"`
	Details       pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateCertificateFinding(ctx context.Context, arg AssessCreateCertificateFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateCertificateFinding,
		arg.DomainID,
		arg.CertificateID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateDKIMFinding = `-- name: AssessCreateDKIMFinding :one
INSERT INTO dkim_findings (domain_id,
                           txt_record_id,
                           severity,
                           status,
                           selector,
                           issue_type,
                           dkim_value,
                           details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (domain_id, issue_type, selector)
WHERE selector IS NOT NULL
    DO UPDATE SET txt_record_id = $2,
                  severity      = $3,
                  status        = $4,
                  dkim_value    = $7,
                  details       = $8
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateDKIMFindingParams struct {
	DomainID    pgtype.Int4     `json:"domain_id"`
	TxtRecordID pgtype.Int4     `json:"txt_record_id"`
	Severity    FindingSeverity `json:"severity"`
	Status      FindingStatus   `json:"status"`
	Selector    pgtype.Text     `json:"selector"`
	IssueType   string          `json:"issue_type"`
	DkimValue   pgtype.Text     `json:"dkim_value"`
	Details     pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateDKIMFinding(ctx context.Context, arg AssessCreateDKIMFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateDKIMFinding,
		arg.DomainID,
		arg.TxtRecordID,
		arg.Severity,
		arg.Status,
		arg.Selector,
		arg.IssueType,
		arg.DkimValue,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateDKIMFindingNoSelector = `-- name: AssessCreateDKIMFindingNoSelector :one
INSERT INTO dkim_findings (domain_id,
                           txt_record_id,
                           severity,
                           status,
                           selector,
                           issue_type,
                           dkim_value,
                           details)
VALUES ($1, $2, $3, $4, NULL, $5, $6, $7)
ON CONFLICT (domain_id, issue_type)
    WHERE (selector IS NULL)
    DO UPDATE SET txt_record_id = $2,
                  severity      = $3,
                  status        = $4,
                  dkim_value    = $6,
                  details       = $7
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateDKIMFindingNoSelectorParams struct {
	DomainID    pgtype.Int4     `json:"domain_id"`
	TxtRecordID pgtype.Int4     `json:"txt_record_id"`
	Severity    FindingSeverity `json:"severity"`
	Status      FindingStatus   `json:"status"`
	IssueType   string          `json:"issue_type"`
	DkimValue   pgtype.Text     `json:"dkim_value"`
	Details     pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateDKIMFindingNoSelector(ctx context.Context, arg AssessCreateDKIMFindingNoSelectorParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateDKIMFindingNoSelector,
		arg.DomainID,
		arg.TxtRecordID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.DkimValue,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateDMARCFinding = `-- name: AssessCreateDMARCFinding :one
INSERT INTO dmarc_findings (domain_id,
                            txt_record_id,
                            severity,
                            status,
                            policy,
                            issue_type,
                            dmarc_value,
                            details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (domain_id, issue_type)
    DO UPDATE SET txt_record_id = $2,
                  severity      = $3,
                  status        = $4,
                  policy        = $5,
                  dmarc_value  = $7,
                  details       = $8
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateDMARCFindingParams struct {
	DomainID    pgtype.Int4     `json:"domain_id"`
	TxtRecordID pgtype.Int4     `json:"txt_record_id"`
	Severity    FindingSeverity `json:"severity"`
	Status      FindingStatus   `json:"status"`
	Policy      pgtype.Text     `json:"policy"`
	IssueType   string          `json:"issue_type"`
	DmarcValue  pgtype.Text     `json:"dmarc_value"`
	Details     pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateDMARCFinding(ctx context.Context, arg AssessCreateDMARCFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateDMARCFinding,
		arg.DomainID,
		arg.TxtRecordID,
		arg.Severity,
		arg.Status,
		arg.Policy,
		arg.IssueType,
		arg.DmarcValue,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateDNSResolutionConsistencyFinding = `-- name: AssessCreateDNSResolutionConsistencyFinding :one
INSERT INTO dns_resolution_consistency_findings (domain_id,
                                                 severity,
                                                 status,
                                                 record_type,
                                                 resolver1,
                                                 resolver1_result,
                                                 resolver2,
                                                 resolver2_result,
                                                 details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (domain_id, record_type)
    DO UPDATE SET severity         = $2,
                  status           = $3,
                  resolver1        = $5,
                  resolver1_result = $6,
                  resolver2        = $7,
                  resolver2_result = $8,
                  details          = $9
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateDNSResolutionConsistencyFindingParams struct {
	DomainID        pgtype.Int4     `json:"domain_id"`
	Severity        FindingSeverity `json:"severity"`
	Status          FindingStatus   `json:"status"`
	RecordType      string          `json:"record_type"`
	Resolver1       string          `json:"resolver1"`
	Resolver1Result pgtype.Text     `json:"resolver1_result"`
	Resolver2       string          `json:"resolver2"`
	Resolver2Result pgtype.Text     `json:"resolver2_result"`
	Details         pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateDNSResolutionConsistencyFinding(ctx context.Context, arg AssessCreateDNSResolutionConsistencyFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateDNSResolutionConsistencyFinding,
		arg.DomainID,
		arg.Severity,
		arg.Status,
		arg.RecordType,
		arg.Resolver1,
		arg.Resolver1Result,
		arg.Resolver2,
		arg.Resolver2Result,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateDNSResolutionLatencyFinding = `-- name: AssessCreateDNSResolutionLatencyFinding :one
INSERT INTO dns_resolution_latency_findings (domain_id,
                                             severity,
                                             status,
                                             record_type,
                                             resolver,
                                             latency_ms,
                                             threshold_ms,
                                             details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (domain_id, resolver, record_type)
    DO UPDATE SET severity     = $2,
                  status       = $3,
                  latency_ms   = $6,
                  threshold_ms = $7,
                  details      = $8
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateDNSResolutionLatencyFindingParams struct {
	DomainID    pgtype.Int4     `json:"domain_id"`
	Severity    FindingSeverity `json:"severity"`
	Status      FindingStatus   `json:"status"`
	RecordType  string          `json:"record_type"`
	Resolver    string          `json:"resolver"`
	LatencyMs   int32           `json:"latency_ms"`
	ThresholdMs int32           `json:"threshold_ms"`
	Details     pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateDNSResolutionLatencyFinding(ctx context.Context, arg AssessCreateDNSResolutionLatencyFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateDNSResolutionLatencyFinding,
		arg.DomainID,
		arg.Severity,
		arg.Status,
		arg.RecordType,
		arg.Resolver,
		arg.LatencyMs,
		arg.ThresholdMs,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateDNSSECFinding = `-- name: AssessCreateDNSSECFinding :one
INSERT INTO dnssec_findings (domain_id,
                             severity,
                             status,
                             issue_type,
                             details)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (domain_id, issue_type)
    DO UPDATE SET severity = $2,
                  status   = $3,
                  details  = $5
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateDNSSECFindingParams struct {
	DomainID  pgtype.Int4     `json:"domain_id"`
	Severity  FindingSeverity `json:"severity"`
	Status    FindingStatus   `json:"status"`
	IssueType string          `json:"issue_type"`
	Details   pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateDNSSECFinding(ctx context.Context, arg AssessCreateDNSSECFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateDNSSECFinding,
		arg.DomainID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateEmailAuthComplianceFinding = `-- name: AssessCreateEmailAuthComplianceFinding :one
INSERT INTO email_auth_compliance_findings (domain_id,
                                            txt_record_id,
                                            severity,
                                            status,
                                            auth_type,
                                            issue_type,
                                            standard_name,
                                            details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (domain_id, auth_type, issue_type)
    DO UPDATE SET txt_record_id = $2,
                  severity      = $3,
                  status        = $4,
                  standard_name = $7,
                  details       = $8
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateEmailAuthComplianceFindingParams struct {
	DomainID     pgtype.Int4     `json:"domain_id"`
	TxtRecordID  pgtype.Int4     `json:"txt_record_id"`
	Severity     FindingSeverity `json:"severity"`
	Status       FindingStatus   `json:"status"`
	AuthType     string          `json:"auth_type"`
	IssueType    string          `json:"issue_type"`
	StandardName pgtype.Text     `json:"standard_name"`
	Details      pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateEmailAuthComplianceFinding(ctx context.Context, arg AssessCreateEmailAuthComplianceFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateEmailAuthComplianceFinding,
		arg.DomainID,
		arg.TxtRecordID,
		arg.Severity,
		arg.Status,
		arg.AuthType,
		arg.IssueType,
		arg.StandardName,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateMinimumRecordSetFinding = `-- name: AssessCreateMinimumRecordSetFinding :one
INSERT INTO minimum_record_set_findings (domain_id,
                                         severity,
                                         status,
                                         issue_type,
                                         missing_record_type,
                                         details)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (domain_id, issue_type)
    DO UPDATE SET severity            = $2,
                  status              = $3,
                  missing_record_type = $5,
                  details             = $6
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateMinimumRecordSetFindingParams struct {
	DomainID          pgtype.Int4     `json:"domain_id"`
	Severity          FindingSeverity `json:"severity"`
	Status            FindingStatus   `json:"status"`
	IssueType         string          `json:"issue_type"`
	MissingRecordType string          `json:"missing_record_type"`
	Details           pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateMinimumRecordSetFinding(ctx context.Context, arg AssessCreateMinimumRecordSetFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateMinimumRecordSetFinding,
		arg.DomainID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.MissingRecordType,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateNSConfigurationFinding = `-- name: AssessCreateNSConfigurationFinding :one
INSERT INTO ns_configuration_findings (domain_id,
                                       ns_record_id,
                                       severity,
                                       status,
                                       issue_type,
                                       nameserver,
                                       details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (domain_id, nameserver, issue_type)
    DO UPDATE SET ns_record_id = $2,
                  severity     = $3,
                  status       = $4,
                  details      = $7
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateNSConfigurationFindingParams struct {
	DomainID   pgtype.Int4     `json:"domain_id"`
	NsRecordID pgtype.Int4     `json:"ns_record_id"`
	Severity   FindingSeverity `json:"severity"`
	Status     FindingStatus   `json:"status"`
	IssueType  string          `json:"issue_type"`
	Nameserver string          `json:"nameserver"`
	Details    pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateNSConfigurationFinding(ctx context.Context, arg AssessCreateNSConfigurationFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateNSConfigurationFinding,
		arg.DomainID,
		arg.NsRecordID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.Nameserver,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateNameserverReachabilityFinding = `-- name: AssessCreateNameserverReachabilityFinding :one
INSERT INTO nameserver_reachability_findings (domain_id,
                                              ns_record_id,
                                              severity,
                                              status,
                                              nameserver,
                                              issue_type,
                                              response_time_ms,
                                              details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (domain_id, nameserver, issue_type)
    DO UPDATE SET ns_record_id     = $2,
                  severity         = $3,
                  status           = $4,
                  response_time_ms = $7,
                  details          = $8
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateNameserverReachabilityFindingParams struct {
	DomainID       pgtype.Int4     `json:"domain_id"`
	NsRecordID     pgtype.Int4     `json:"ns_record_id"`
	Severity       FindingSeverity `json:"severity"`
	Status         FindingStatus   `json:"status"`
	Nameserver     string          `json:"nameserver"`
	IssueType      string          `json:"issue_type"`
	ResponseTimeMs pgtype.Int4     `json:"response_time_ms"`
	Details        pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateNameserverReachabilityFinding(ctx context.Context, arg AssessCreateNameserverReachabilityFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateNameserverReachabilityFinding,
		arg.DomainID,
		arg.NsRecordID,
		arg.Severity,
		arg.Status,
		arg.Nameserver,
		arg.IssueType,
		arg.ResponseTimeMs,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateNameserverRedundancyFinding = `-- name: AssessCreateNameserverRedundancyFinding :one
INSERT INTO nameserver_redundancy_findings (domain_id,
                                            severity,
                                            status,
                                            issue_type,
                                            nameserver_count,
                                            recommended_count,
                                            details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (domain_id, issue_type)
    DO UPDATE SET severity          = $2,
                  status            = $3,
                  nameserver_count  = $5,
                  recommended_count = $6,
                  details           = $7
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateNameserverRedundancyFindingParams struct {
	DomainID         pgtype.Int4     `json:"domain_id"`
	Severity         FindingSeverity `json:"severity"`
	Status           FindingStatus   `json:"status"`
	IssueType        string          `json:"issue_type"`
	NameserverCount  int32           `json:"nameserver_count"`
	RecommendedCount int32           `json:"recommended_count"`
	Details          pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateNameserverRedundancyFinding(ctx context.Context, arg AssessCreateNameserverRedundancyFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateNameserverRedundancyFinding,
		arg.DomainID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.NameserverCount,
		arg.RecommendedCount,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessCreateSPFFinding = `-- name: AssessCreateSPFFinding :one
INSERT INTO spf_findings (domain_id,
                          txt_record_id,
                          severity,
                          status,
                          issue_type,
                          spf_value,
                          details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (domain_id, issue_type)
    DO UPDATE SET txt_record_id = $2,
                  severity      = $3,
                  status        = $4,
                  spf_value     = $6,
                  details       = $7
RETURNING (xmax = 0)::boolean AS inserted
`

type AssessCreateSPFFindingParams struct {
	DomainID    pgtype.Int4     `json:"domain_id"`
	TxtRecordID pgtype.Int4     `json:"txt_record_id"`
	Severity    FindingSeverity `json:"severity"`
	Status      FindingStatus   `json:"status"`
	IssueType   string          `json:"issue_type"`
	SpfValue    pgtype.Text     `json:"spf_value"`
	Details     pgtype.Text     `json:"details"`
}

func (q *Queries) AssessCreateSPFFinding(ctx context.Context, arg AssessCreateSPFFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, assessCreateSPFFinding,
		arg.DomainID,
		arg.TxtRecordID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.SpfValue,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const assessDKIMFindingsByDomainID = `-- name: AssessDKIMFindingsByDomainID :many
SELECT df.id, df.uid, df.domain_id, df.txt_record_id, df.severity, df.status, df.selector, df.issue_type, df.details, df.dkim_value, df.created_at, df.updated_at
FROM dkim_findings df
         JOIN domains d ON df.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY df.severity ASC, df.created_at DESC
`

type AssessDKIMFindingsByDomainIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessDKIMFindingsByDomainID(ctx context.Context, arg AssessDKIMFindingsByDomainIDParams) ([]DkimFindings, error) {
	rows, err := q.db.Query(ctx, assessDKIMFindingsByDomainID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DkimFindings{}
	for rows.Next() {
		var i DkimFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.TxtRecordID,
			&i.Severity,
			&i.Status,
			&i.Selector,
			&i.IssueType,
			&i.Details,
			&i.DkimValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetCAAComplianceFindingsByDomainUID = `-- name: AssessGetCAAComplianceFindingsByDomainUID :many
SELECT ccf.id, ccf.uid, ccf.domain_id, ccf.caa_record_id, ccf.severity, ccf.status, ccf.issue_type, ccf.standard_name, ccf.details, ccf.created_at, ccf.updated_at
FROM caa_compliance_findings ccf
         JOIN domains d ON ccf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY ccf.severity ASC, ccf.created_at DESC
`

type AssessGetCAAComplianceFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetCAAComplianceFindingsByDomainUID(ctx context.Context, arg AssessGetCAAComplianceFindingsByDomainUIDParams) ([]CaaComplianceFindings, error) {
	rows, err := q.db.Query(ctx, assessGetCAAComplianceFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaaComplianceFindings{}
	for rows.Next() {
		var i CaaComplianceFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.CaaRecordID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.StandardName,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetCAAConfigurationFindingsByDomainUID = `-- name: AssessGetCAAConfigurationFindingsByDomainUID :many
SELECT ccf.id, ccf.uid, ccf.domain_id, ccf.caa_record_id, ccf.severity, ccf.status, ccf.issue_type, ccf.details, ccf.created_at, ccf.updated_at
FROM caa_configuration_findings ccf
         JOIN domains d ON ccf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY ccf.severity ASC, ccf.created_at DESC
`

type AssessGetCAAConfigurationFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetCAAConfigurationFindingsByDomainUID(ctx context.Context, arg AssessGetCAAConfigurationFindingsByDomainUIDParams) ([]CaaConfigurationFindings, error) {
	rows, err := q.db.Query(ctx, assessGetCAAConfigurationFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaaConfigurationFindings{}
	for rows.Next() {
		var i CaaConfigurationFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.CaaRecordID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetCertificateFindingsByDomainUID = `-- name: AssessGetCertificateFindingsByDomainUID :many
SELECT cf.id, cf.uid, cf.domain_id, cf.certificate_id, cf.severity, cf.status, cf.issue_type, cf.details, cf.created_at, cf.updated_at
FROM certificate_findings cf
         JOIN domains d ON cf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY cf.severity ASC, cf.created_at DESC
`

type AssessGetCertificateFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetCertificateFindingsByDomainUID(ctx context.Context, arg AssessGetCertificateFindingsByDomainUIDParams) ([]CertificateFindings, error) {
	rows, err := q.db.Query(ctx, assessGetCertificateFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CertificateFindings{}
	for rows.Next() {
		var i CertificateFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.CertificateID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetCnameRedirectionFindingsByDomainUID = `-- name: AssessGetCnameRedirectionFindingsByDomainUID :many
SELECT crf.id, crf.uid, crf.domain_id, crf.cname_record_id, crf.severity, crf.status, crf.issue_type, crf.chain_length, crf.details, crf.created_at, crf.updated_at
FROM cname_redirection_findings crf
         JOIN domains d ON crf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY crf.severity ASC, crf.created_at DESC
`

type AssessGetCnameRedirectionFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetCnameRedirectionFindingsByDomainUID(ctx context.Context, arg AssessGetCnameRedirectionFindingsByDomainUIDParams) ([]CnameRedirectionFindings, error) {
	rows, err := q.db.Query(ctx, assessGetCnameRedirectionFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CnameRedirectionFindings{}
	for rows.Next() {
		var i CnameRedirectionFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.CnameRecordID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.ChainLength,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetDKIMFindings = `-- name: AssessGetDKIMFindings :many
SELECT id, uid, domain_id, txt_record_id, severity, status, selector, issue_type, details, dkim_value, created_at, updated_at
FROM dkim_findings
WHERE domain_id = $1
ORDER BY severity ASC, created_at DESC
`

func (q *Queries) AssessGetDKIMFindings(ctx context.Context, domainID pgtype.Int4) ([]DkimFindings, error) {
	rows, err := q.db.Query(ctx, assessGetDKIMFindings, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DkimFindings{}
	for rows.Next() {
		var i DkimFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.TxtRecordID,
			&i.Severity,
			&i.Status,
			&i.Selector,
			&i.IssueType,
			&i.Details,
			&i.DkimValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetDMARCFindings = `-- name: AssessGetDMARCFindings :many
SELECT id, uid, domain_id, txt_record_id, severity, status, policy, issue_type, details, dmarc_value, created_at, updated_at
FROM dmarc_findings
WHERE domain_id = $1
ORDER BY severity ASC, created_at DESC
`

func (q *Queries) AssessGetDMARCFindings(ctx context.Context, domainID pgtype.Int4) ([]DmarcFindings, error) {
	rows, err := q.db.Query(ctx, assessGetDMARCFindings, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DmarcFindings{}
	for rows.Next() {
		var i DmarcFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.TxtRecordID,
			&i.Severity,
			&i.Status,
			&i.Policy,
			&i.IssueType,
			&i.Details,
			&i.DmarcValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetDMARCFindingsByDomainID = `-- name: AssessGetDMARCFindingsByDomainID :many
SELECT df.id, df.uid, df.domain_id, df.txt_record_id, df.severity, df.status, df.policy, df.issue_type, df.details, df.dmarc_value, df.created_at, df.updated_at
FROM dmarc_findings df
         JOIN domains d ON df.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY df.severity ASC, df.created_at DESC
`

type AssessGetDMARCFindingsByDomainIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetDMARCFindingsByDomainID(ctx context.Context, arg AssessGetDMARCFindingsByDomainIDParams) ([]DmarcFindings, error) {
	rows, err := q.db.Query(ctx, assessGetDMARCFindingsByDomainID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DmarcFindings{}
	for rows.Next() {
		var i DmarcFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.TxtRecordID,
			&i.Severity,
			&i.Status,
			&i.Policy,
			&i.IssueType,
			&i.Details,
			&i.DmarcValue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetDNSResolutionConsistencyFindingsByDomainUID = `-- name: AssessGetDNSResolutionConsistencyFindingsByDomainUID :many
SELECT con.id, con.uid, con.domain_id, con.severity, con.status, con.record_type, con.resolver1, con.resolver1_result, con.resolver2, con.resolver2_result, con.details, con.created_at, con.updated_at
FROM dns_resolution_consistency_findings con
         JOIN domains d ON con.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY con.severity ASC, con.created_at DESC
`

type AssessGetDNSResolutionConsistencyFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetDNSResolutionConsistencyFindingsByDomainUID(ctx context.Context, arg AssessGetDNSResolutionConsistencyFindingsByDomainUIDParams) ([]DnsResolutionConsistencyFindings, error) {
	rows, err := q.db.Query(ctx, assessGetDNSResolutionConsistencyFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsResolutionConsistencyFindings{}
	for rows.Next() {
		var i DnsResolutionConsistencyFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.Severity,
			&i.Status,
			&i.RecordType,
			&i.Resolver1,
			&i.Resolver1Result,
			&i.Resolver2,
			&i.Resolver2Result,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetDNSResolutionLatencyFindingsByDomainUID = `-- name: AssessGetDNSResolutionLatencyFindingsByDomainUID :many
SELECT lat.id, lat.uid, lat.domain_id, lat.severity, lat.status, lat.record_type, lat.resolver, lat.latency_ms, lat.threshold_ms, lat.details, lat.created_at, lat.updated_at
FROM dns_resolution_latency_findings lat
         JOIN domains d ON lat.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY lat.severity ASC, lat.created_at DESC
`

type AssessGetDNSResolutionLatencyFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetDNSResolutionLatencyFindingsByDomainUID(ctx context.Context, arg AssessGetDNSResolutionLatencyFindingsByDomainUIDParams) ([]DnsResolutionLatencyFindings, error) {
	rows, err := q.db.Query(ctx, assessGetDNSResolutionLatencyFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnsResolutionLatencyFindings{}
	for rows.Next() {
		var i DnsResolutionLatencyFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.Severity,
			&i.Status,
			&i.RecordType,
			&i.Resolver,
			&i.LatencyMs,
			&i.ThresholdMs,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetDNSSECFindingsByDomainUID = `-- name: AssessGetDNSSECFindingsByDomainUID :many
SELECT df.id, df.uid, df.domain_id, df.dnskey_record_id, df.ds_record_id, df.severity, df.status, df.issue_type, df.details, df.created_at, df.updated_at
FROM dnssec_findings df
         JOIN domains d ON df.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY df.severity ASC, df.created_at DESC
`

type AssessGetDNSSECFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetDNSSECFindingsByDomainUID(ctx context.Context, arg AssessGetDNSSECFindingsByDomainUIDParams) ([]DnssecFindings, error) {
	rows, err := q.db.Query(ctx, assessGetDNSSECFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DnssecFindings{}
	for rows.Next() {
		var i DnssecFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.DnskeyRecordID,
			&i.DsRecordID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetDanglingCnameFindingsByDomainUID = `-- name: AssessGetDanglingCnameFindingsByDomainUID :many
SELECT dcf.id, dcf.uid, dcf.domain_id, dcf.severity, dcf.status, dcf.target_domain, dcf.service_provider, dcf.takeover_possible, dcf.details, dcf.created_at, dcf.updated_at
FROM dangling_cname_findings dcf
         JOIN domains d ON dcf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY dcf.severity ASC, dcf.created_at DESC
`

type AssessGetDanglingCnameFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetDanglingCnameFindingsByDomainUID(ctx context.Context, arg AssessGetDanglingCnameFindingsByDomainUIDParams) ([]DanglingCnameFindings, error) {
	rows, err := q.db.Query(ctx, assessGetDanglingCnameFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DanglingCnameFindings{}
	for rows.Next() {
		var i DanglingCnameFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.Severity,
			&i.Status,
			&i.TargetDomain,
			&i.ServiceProvider,
			&i.TakeoverPossible,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetEmailAuthComplianceFindingsByDomainUID = `-- name: AssessGetEmailAuthComplianceFindingsByDomainUID :many
SELECT eacf.id, eacf.uid, eacf.domain_id, eacf.txt_record_id, eacf.severity, eacf.status, eacf.auth_type, eacf.issue_type, eacf.standard_name, eacf.details, eacf.created_at, eacf.updated_at
FROM email_auth_compliance_findings eacf
         JOIN domains d ON eacf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY eacf.severity ASC, eacf.created_at DESC
`

type AssessGetEmailAuthComplianceFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetEmailAuthComplianceFindingsByDomainUID(ctx context.Context, arg AssessGetEmailAuthComplianceFindingsByDomainUIDParams) ([]EmailAuthComplianceFindings, error) {
	rows, err := q.db.Query(ctx, assessGetEmailAuthComplianceFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailAuthComplianceFindings{}
	for rows.Next() {
		var i EmailAuthComplianceFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.TxtRecordID,
			&i.Severity,
			&i.Status,
			&i.AuthType,
			&i.IssueType,
			&i.StandardName,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetMinimumRecordSetFindingsByDomainUID = `-- name: AssessGetMinimumRecordSetFindingsByDomainUID :many
SELECT mrf.id, mrf.uid, mrf.domain_id, mrf.severity, mrf.status, mrf.issue_type, mrf.missing_record_type, mrf.details, mrf.created_at, mrf.updated_at
FROM minimum_record_set_findings mrf
         JOIN domains d ON mrf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY mrf.severity ASC, mrf.created_at DESC
`

type AssessGetMinimumRecordSetFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetMinimumRecordSetFindingsByDomainUID(ctx context.Context, arg AssessGetMinimumRecordSetFindingsByDomainUIDParams) ([]MinimumRecordSetFindings, error) {
	rows, err := q.db.Query(ctx, assessGetMinimumRecordSetFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MinimumRecordSetFindings{}
	for rows.Next() {
		var i MinimumRecordSetFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.MissingRecordType,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetNSConfigurationFindingsByDomainUID = `-- name: AssessGetNSConfigurationFindingsByDomainUID :many
SELECT ncf.id, ncf.uid, ncf.domain_id, ncf.ns_record_id, ncf.severity, ncf.status, ncf.issue_type, ncf.nameserver, ncf.details, ncf.created_at, ncf.updated_at
FROM ns_configuration_findings ncf
         JOIN domains d ON ncf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY ncf.severity ASC, ncf.created_at DESC
`

type AssessGetNSConfigurationFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetNSConfigurationFindingsByDomainUID(ctx context.Context, arg AssessGetNSConfigurationFindingsByDomainUIDParams) ([]NsConfigurationFindings, error) {
	rows, err := q.db.Query(ctx, assessGetNSConfigurationFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NsConfigurationFindings{}
	for rows.Next() {
		var i NsConfigurationFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.NsRecordID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.Nameserver,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetNameserverReachabilityFindingsByDomainUID = `-- name: AssessGetNameserverReachabilityFindingsByDomainUID :many
SELECT rch.id, rch.uid, rch.domain_id, rch.ns_record_id, rch.severity, rch.status, rch.nameserver, rch.issue_type, rch.response_time_ms, rch.details, rch.created_at, rch.updated_at
FROM nameserver_reachability_findings rch
         JOIN domains d ON rch.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY rch.severity ASC, rch.created_at DESC
`

type AssessGetNameserverReachabilityFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetNameserverReachabilityFindingsByDomainUID(ctx context.Context, arg AssessGetNameserverReachabilityFindingsByDomainUIDParams) ([]NameserverReachabilityFindings, error) {
	rows, err := q.db.Query(ctx, assessGetNameserverReachabilityFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NameserverReachabilityFindings{}
	for rows.Next() {
		var i NameserverReachabilityFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.NsRecordID,
			&i.Severity,
			&i.Status,
			&i.Nameserver,
			&i.IssueType,
			&i.ResponseTimeMs,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetNameserverRedundancyFindingsByDomainUID = `-- name: AssessGetNameserverRedundancyFindingsByDomainUID :many
SELECT nrf.id, nrf.uid, nrf.domain_id, nrf.severity, nrf.status, nrf.issue_type, nrf.nameserver_count, nrf.recommended_count, nrf.details, nrf.created_at, nrf.updated_at
FROM nameserver_redundancy_findings nrf
         JOIN domains d ON nrf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY nrf.severity ASC, nrf.created_at DESC
`

type AssessGetNameserverRedundancyFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetNameserverRedundancyFindingsByDomainUID(ctx context.Context, arg AssessGetNameserverRedundancyFindingsByDomainUIDParams) ([]NameserverRedundancyFindings, error) {
	rows, err := q.db.Query(ctx, assessGetNameserverRedundancyFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NameserverRedundancyFindings{}
	for rows.Next() {
		var i NameserverRedundancyFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.NameserverCount,
			&i.RecommendedCount,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetSPFFindingByDomainID = `-- name: AssessGetSPFFindingByDomainID :many
SELECT sf.id, sf.uid, sf.domain_id, sf.txt_record_id, sf.severity, sf.status, sf.issue_type, sf.spf_value, sf.details, sf.created_at, sf.updated_at
FROM spf_findings sf
         JOIN domains d ON sf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY sf.severity ASC, sf.created_at DESC
`

type AssessGetSPFFindingByDomainIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetSPFFindingByDomainID(ctx context.Context, arg AssessGetSPFFindingByDomainIDParams) ([]SpfFindings, error) {
	rows, err := q.db.Query(ctx, assessGetSPFFindingByDomainID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpfFindings{}
	for rows.Next() {
		var i SpfFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.TxtRecordID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.SpfValue,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetSPFFindings = `-- name: AssessGetSPFFindings :many
SELECT id, uid, domain_id, txt_record_id, severity, status, issue_type, spf_value, details, created_at, updated_at
FROM spf_findings
WHERE domain_id = $1
ORDER BY severity ASC, created_at DESC
`

func (q *Queries) AssessGetSPFFindings(ctx context.Context, domainID pgtype.Int4) ([]SpfFindings, error) {
	rows, err := q.db.Query(ctx, assessGetSPFFindings, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SpfFindings{}
	for rows.Next() {
		var i SpfFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.TxtRecordID,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.SpfValue,
			&i.Details,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetZoneTransferFindings = `-- name: AssessGetZoneTransferFindings :many
SELECT id, uid, domain_id, ns_record_id, severity, status, nameserver, zone_transfer_possible,
       transfer_type, details, transfer_details, created_at, updated_at
FROM zone_transfer_findings
WHERE domain_id = $1
ORDER BY severity ASC, created_at DESC
`

func (q *Queries) AssessGetZoneTransferFindings(ctx context.Context, domainID pgtype.Int4) ([]ZoneTransferFindings, error) {
	rows, err := q.db.Query(ctx, assessGetZoneTransferFindings, domainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZoneTransferFindings{}
	for rows.Next() {
		var i ZoneTransferFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.NsRecordID,
			&i.Severity,
			&i.Status,
			&i.Nameserver,
			&i.ZoneTransferPossible,
			&i.TransferType,
			&i.Details,
			&i.TransferDetails,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const assessGetZoneTransferFindingsByDomainUID = `-- name: AssessGetZoneTransferFindingsByDomainUID :many
SELECT ztf.id, ztf.uid, ztf.domain_id, ztf.ns_record_id, ztf.severity, ztf.status, ztf.nameserver, ztf.zone_transfer_possible, ztf.transfer_type, ztf.details, ztf.transfer_details, ztf.created_at, ztf.updated_at
FROM zone_transfer_findings ztf
         JOIN domains d ON ztf.domain_id = d.id
WHERE d.uid = $1
  AND d.tenant_id = $2
ORDER BY ztf.severity ASC, ztf.created_at DESC
`

type AssessGetZoneTransferFindingsByDomainUIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) AssessGetZoneTransferFindingsByDomainUID(ctx context.Context, arg AssessGetZoneTransferFindingsByDomainUIDParams) ([]ZoneTransferFindings, error) {
	rows, err := q.db.Query(ctx, assessGetZoneTransferFindingsByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ZoneTransferFindings{}
	for rows.Next() {
		var i ZoneTransferFindings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.DomainID,
			&i.NsRecordID,
			&i.Severity,
			&i.Status,
			&i.Nameserver,
			&i.ZoneTransferPossible,
			&i.TransferType,
			&i.Details,
			&i.TransferDetails,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainsListFindingsSummary = `-- name: DomainsListFindingsSummary :many
WITH ids AS (
    SELECT unnest($2::int[]) AS domain_id
),
open_findings AS (
    SELECT domain_id, severity::text AS severity, uid, 'SPF'::text AS kind, issue_type FROM spf_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'DKIM'::text, issue_type FROM dkim_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'DMARC'::text, issue_type FROM dmarc_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'ZONE'::text,
           CASE WHEN zone_transfer_possible THEN 'zone_transfer_exposed' ELSE 'zone_transfer_refused' END
        FROM zone_transfer_findings
        WHERE zone_transfer_possible = true AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'CERT'::text, issue_type FROM certificate_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'DNSSEC'::text, issue_type FROM dnssec_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'DANGLING'::text,
           CASE WHEN takeover_possible THEN 'subdomain_takeover' ELSE 'dangling_cname' END
        FROM dangling_cname_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'CNAME'::text, issue_type FROM cname_redirection_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'CAA_CONFIG'::text, issue_type FROM caa_configuration_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'CAA_COMPLIANCE'::text, issue_type FROM caa_compliance_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'MIN_RECORDS'::text, issue_type FROM minimum_record_set_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'EMAIL_COMPLIANCE'::text, issue_type FROM email_auth_compliance_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'NS_CONFIG'::text, issue_type FROM ns_configuration_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'NS_REDUNDANCY'::text, issue_type FROM nameserver_redundancy_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'NS_REACHABILITY'::text, issue_type FROM nameserver_reachability_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'NS_LATENCY'::text, 'high_latency'::text FROM dns_resolution_latency_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
    UNION ALL
    SELECT domain_id, severity::text, uid, 'NS_CONSISTENCY'::text, 'resolver_mismatch'::text FROM dns_resolution_consistency_findings
        WHERE status = 'open' AND domain_id = ANY($2::int[])
)
SELECT
    ids.domain_id::int AS domain_id,
    MIN(CASE f.severity
        WHEN 'critical' THEN 1
        WHEN 'high'     THEN 2
        WHEN 'medium'   THEN 3
        WHEN 'low'      THEN 4
        WHEN 'info'     THEN 5
        ELSE 6
    END)::int AS severity_rank,
    COUNT(f.severity)::int AS finding_count
FROM ids
LEFT JOIN open_findings f ON f.domain_id = ids.domain_id
    AND NOT EXISTS (
        SELECT 1 FROM finding_suppressions s
        WHERE s.tenant_id = $1
          AND (s.expires_at IS NULL OR s.expires_at > now())
          AND (s.finding_uid = f.uid
            OR (s.finding_uid IS NULL AND s.kind = f.kind AND s.issue_type = f.issue_type
                AND (s.domain_id IS NULL OR s.domain_id = f.domain_id)))
    )
GROUP BY ids.domain_id
`

type DomainsListFindingsSummaryParams struct {
	TenantID  int32   `json:"tenant_id"`
	DomainIds []int32 `json:"domain_ids"`
}

type DomainsListFindingsSummaryRow struct {
	DomainID     int32 `json:"domain_id"`
	SeverityRank int32 `json:"severity_rank"`
	FindingCount int32 `json:"finding_count"`
}

// Worst open-finding severity + open-finding count per domain, for a page of
// domain IDs. One round-trip for the whole page (no N+1). Only actionable
// findings count: status='open' for email findings, zone_transfer_possible for
// AXFR. severity_rank: critical=1 high=2 medium=3 low=4 info=5 none=6.
//
// Suppressed findings (active silence rule or ack — see finding_suppressions) are
// excluded from both the rank and the count so a silenced check never reddens a
// domain's badge. The kind/issue_type literals must match FindingsListByTenant.
func (q *Queries) DomainsListFindingsSummary(ctx context.Context, arg DomainsListFindingsSummaryParams) ([]DomainsListFindingsSummaryRow, error) {
	rows, err := q.db.Query(ctx, domainsListFindingsSummary, arg.TenantID, arg.DomainIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainsListFindingsSummaryRow{}
	for rows.Next() {
		var i DomainsListFindingsSummaryRow
		if err := rows.Scan(&i.DomainID, &i.SeverityRank, &i.FindingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findingsListByTenant = `-- name: FindingsListByTenant :many
SELECT a.finding_uid,
       a.domain_uid,
       a.domain_name,
       a.kind,
       a.severity,
       a.status,
       a.issue_type,
       a.value,
       a.details,
       a.selector,
       a.created_at,
       a.is_suppressed
FROM (SELECT f.finding_uid, f.domain_id, f.domain_uid, f.domain_name, f.kind, f.severity, f.status, f.issue_type, f.value, f.details, f.selector, f.created_at,
             EXISTS (SELECT 1
                     FROM finding_suppressions s
                     WHERE s.tenant_id = $1
                       AND (s.expires_at IS NULL OR s.expires_at > now())
                       AND (s.finding_uid = f.finding_uid
                         OR (s.finding_uid IS NULL
                             AND s.kind = f.kind
                             AND s.issue_type = f.issue_type
                             AND (s.domain_id IS NULL OR s.domain_id = f.domain_id)))) AS is_suppressed
      FROM (SELECT sf.uid                AS finding_uid,
                   d.id                  AS domain_id,
                   d.uid                 AS domain_uid,
                   d.name                AS domain_name,
                   'SPF'::text           AS kind,
                   sf.severity           AS severity,
                   sf.status             AS status,
                   sf.issue_type         AS issue_type,
                   sf.spf_value          AS value,
                   sf.details            AS details,
                   NULL::text            AS selector,
                   sf.created_at         AS created_at
            FROM spf_findings sf
                     JOIN domains d ON sf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR sf.status = 'open')

            UNION ALL

            SELECT df.uid, d.id, d.uid, d.name, 'DKIM'::text, df.severity, df.status,
                   df.issue_type, df.dkim_value, df.details, df.selector, df.created_at
            FROM dkim_findings df
                     JOIN domains d ON df.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR df.status = 'open')

            UNION ALL

            SELECT mf.uid, d.id, d.uid, d.name, 'DMARC'::text, mf.severity, mf.status,
                   mf.issue_type, mf.dmarc_value, mf.details, NULL::text, mf.created_at
            FROM dmarc_findings mf
                     JOIN domains d ON mf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR mf.status = 'open')

            UNION ALL

            SELECT zf.uid, d.id, d.uid, d.name, 'ZONE'::text, zf.severity, zf.status,
                   CASE WHEN zf.zone_transfer_possible
                        THEN 'zone_transfer_exposed' ELSE 'zone_transfer_refused' END,
                   zf.nameserver, zf.details, NULL::text, zf.created_at
            FROM zone_transfer_findings zf
                     JOIN domains d ON zf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR zf.zone_transfer_possible = true)

            UNION ALL

            SELECT cf.uid, d.id, d.uid, d.name, 'CERT'::text, cf.severity, cf.status,
                   cf.issue_type, NULL::text, cf.details, NULL::text, cf.created_at
            FROM certificate_findings cf
                     JOIN domains d ON cf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR cf.status = 'open')

            UNION ALL

            SELECT nf.uid, d.id, d.uid, d.name, 'DNSSEC'::text, nf.severity, nf.status,
                   nf.issue_type, NULL::text, nf.details, NULL::text, nf.created_at
            FROM dnssec_findings nf
                     JOIN domains d ON nf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR nf.status = 'open')

            UNION ALL

            SELECT dcf.uid, d.id, d.uid, d.name, 'DANGLING'::text, dcf.severity, dcf.status,
                   CASE WHEN dcf.takeover_possible
                        THEN 'subdomain_takeover' ELSE 'dangling_cname' END,
                   dcf.target_domain, dcf.details, NULL::text, dcf.created_at
            FROM dangling_cname_findings dcf
                     JOIN domains d ON dcf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR dcf.status = 'open')

            UNION ALL

            SELECT crf.uid, d.id, d.uid, d.name, 'CNAME'::text, crf.severity, crf.status,
                   crf.issue_type, NULL::text, crf.details, NULL::text, crf.created_at
            FROM cname_redirection_findings crf
                     JOIN domains d ON crf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR crf.status = 'open')

            UNION ALL

            SELECT ccf.uid, d.id, d.uid, d.name, 'CAA_CONFIG'::text, ccf.severity, ccf.status,
                   ccf.issue_type, NULL::text, ccf.details, NULL::text, ccf.created_at
            FROM caa_configuration_findings ccf
                     JOIN domains d ON ccf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR ccf.status = 'open')

            UNION ALL

            SELECT cpf.uid, d.id, d.uid, d.name, 'CAA_COMPLIANCE'::text, cpf.severity, cpf.status,
                   cpf.issue_type, NULL::text, cpf.details, NULL::text, cpf.created_at
            FROM caa_compliance_findings cpf
                     JOIN domains d ON cpf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR cpf.status = 'open')

            UNION ALL

            SELECT mrf.uid, d.id, d.uid, d.name, 'MIN_RECORDS'::text, mrf.severity, mrf.status,
                   mrf.issue_type, mrf.missing_record_type, mrf.details, NULL::text, mrf.created_at
            FROM minimum_record_set_findings mrf
                     JOIN domains d ON mrf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR mrf.status = 'open')

            UNION ALL

            SELECT eacf.uid, d.id, d.uid, d.name, 'EMAIL_COMPLIANCE'::text, eacf.severity, eacf.status,
                   eacf.issue_type, eacf.auth_type, eacf.details, NULL::text, eacf.created_at
            FROM email_auth_compliance_findings eacf
                     JOIN domains d ON eacf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR eacf.status = 'open')

            UNION ALL

            SELECT ncf.uid, d.id, d.uid, d.name, 'NS_CONFIG'::text, ncf.severity, ncf.status,
                   ncf.issue_type, ncf.nameserver, ncf.details, NULL::text, ncf.created_at
            FROM ns_configuration_findings ncf
                     JOIN domains d ON ncf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR ncf.status = 'open')

            UNION ALL

            SELECT nrf.uid, d.id, d.uid, d.name, 'NS_REDUNDANCY'::text, nrf.severity, nrf.status,
                   nrf.issue_type, nrf.nameserver_count::text, nrf.details, NULL::text, nrf.created_at
            FROM nameserver_redundancy_findings nrf
                     JOIN domains d ON nrf.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR nrf.status = 'open')

            UNION ALL

            SELECT rch.uid, d.id, d.uid, d.name, 'NS_REACHABILITY'::text, rch.severity, rch.status,
                   rch.issue_type, rch.nameserver, rch.details, NULL::text, rch.created_at
            FROM nameserver_reachability_findings rch
                     JOIN domains d ON rch.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR rch.status = 'open')

            UNION ALL

            SELECT lat.uid, d.id, d.uid, d.name, 'NS_LATENCY'::text, lat.severity, lat.status,
                   'high_latency'::text, lat.resolver, lat.details, NULL::text, lat.created_at
            FROM dns_resolution_latency_findings lat
                     JOIN domains d ON lat.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR lat.status = 'open')

            UNION ALL

            SELECT con.uid, d.id, d.uid, d.name, 'NS_CONSISTENCY'::text, con.severity, con.status,
                   'resolver_mismatch'::text, con.record_type, con.details, NULL::text, con.created_at
            FROM dns_resolution_consistency_findings con
                     JOIN domains d ON con.domain_id = d.id
            WHERE d.tenant_id = $1
              AND ($2::bool OR con.status = 'open')) f) a
WHERE ($3::bool OR NOT a.is_suppressed)
ORDER BY a.domain_name ASC,
         CASE a.severity
             WHEN 'critical' THEN 1
             WHEN 'high' THEN 2
             WHEN 'medium' THEN 3
             WHEN 'low' THEN 4
             WHEN 'info' THEN 5
             ELSE 6
             END ASC,
         a.created_at ASC
`

type FindingsListByTenantParams struct {
	TenantID          int32 `json:"tenant_id"`
	IncludeCompliant  bool  `json:"include_compliant"`
	IncludeSuppressed bool  `json:"include_suppressed"`
}

type FindingsListByTenantRow struct {
	FindingUid   string             `json:"finding_uid"`
	DomainUid    string             `json:"domain_uid"`
	DomainName   string             `json:"domain_name"`
	Kind         string             `json:"kind"`
	Severity     FindingSeverity    `json:"severity"`
	Status       FindingStatus      `json:"status"`
	IssueType    string             `json:"issue_type"`
	Value        pgtype.Text        `json:"value"`
	Details      pgtype.Text        `json:"details"`
	Selector     pgtype.Text        `json:"selector"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	IsSuppressed bool               `json:"is_suppressed"`
}

// Every finding across SPF/DKIM/DMARC/zone-transfer for one tenant, in a single
// UNION ALL. Tenant scope is enforced transitively by the domains.tenant_id join
// (the finding tables have no tenant_id) — this join IS the security boundary.
// When @include_compliant is false, email findings are restricted to status='open'
// and zone-transfer to actually-possible AXFRs. Ordered domain-then-severity so
// the handler can group consecutively without a second sort.
//
// is_suppressed flags findings hit by an active silence rule (kind+issue_type,
// tenant-global or per-domain) or a per-finding ack — see finding_suppressions.
// When @include_suppressed is false they are dropped; when true they are returned
// marked so the handler can render them dimmed while still excluding them from
// counts. The kind/issue_type literals here ARE the canonical identity the rules
// match against, so they must stay byte-identical to FindingResolveByUID.
func (q *Queries) FindingsListByTenant(ctx context.Context, arg FindingsListByTenantParams) ([]FindingsListByTenantRow, error) {
	rows, err := q.db.Query(ctx, findingsListByTenant, arg.TenantID, arg.IncludeCompliant, arg.IncludeSuppressed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingsListByTenantRow{}
	for rows.Next() {
		var i FindingsListByTenantRow
		if err := rows.Scan(
			&i.FindingUid,
			&i.DomainUid,
			&i.DomainName,
			&i.Kind,
			&i.Severity,
			&i.Status,
			&i.IssueType,
			&i.Value,
			&i.Details,
			&i.Selector,
			&i.CreatedAt,
			&i.IsSuppressed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeCnameRedirectionFinding = `-- name: StoreCnameRedirectionFinding :one
INSERT INTO cname_redirection_findings (domain_id,
                                        cname_record_id,
                                        severity,
                                        status,
                                        issue_type,
                                        chain_length,
                                        details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (domain_id, issue_type)
    DO UPDATE SET cname_record_id = $2,
                  severity        = $3,
                  status          = $4,
                  chain_length    = $6,
                  details         = $7
RETURNING (xmax = 0)::boolean AS inserted
`

type StoreCnameRedirectionFindingParams struct {
	DomainID      pgtype.Int4     `json:"domain_id"`
	CnameRecordID pgtype.Int4     `json:"cname_record_id"`
	Severity      FindingSeverity `json:"severity"`
	Status        FindingStatus   `json:"status"`
	IssueType     string          `json:"issue_type"`
	ChainLength   pgtype.Int4     `json:"chain_length"`
	Details       pgtype.Text     `json:"details"`
}

func (q *Queries) StoreCnameRedirectionFinding(ctx context.Context, arg StoreCnameRedirectionFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, storeCnameRedirectionFinding,
		arg.DomainID,
		arg.CnameRecordID,
		arg.Severity,
		arg.Status,
		arg.IssueType,
		arg.ChainLength,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const storeDanglingCnameFinding = `-- name: StoreDanglingCnameFinding :one
INSERT INTO dangling_cname_findings (domain_id,
                                     severity,
                                     status,
                                     target_domain,
                                     service_provider,
                                     takeover_possible,
                                     details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (domain_id, target_domain)
    DO UPDATE SET severity          = $2,
                  status            = $3,
                  service_provider  = $5,
                  takeover_possible = $6,
                  details           = $7
RETURNING (xmax = 0)::boolean AS inserted
`

type StoreDanglingCnameFindingParams struct {
	DomainID         pgtype.Int4     `json:"domain_id"`
	Severity         FindingSeverity `json:"severity"`
	Status           FindingStatus   `json:"status"`
	TargetDomain     string          `json:"target_domain"`
	ServiceProvider  pgtype.Text     `json:"service_provider"`
	TakeoverPossible bool            `json:"takeover_possible"`
	Details          pgtype.Text     `json:"details"`
}

func (q *Queries) StoreDanglingCnameFinding(ctx context.Context, arg StoreDanglingCnameFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, storeDanglingCnameFinding,
		arg.DomainID,
		arg.Severity,
		arg.Status,
		arg.TargetDomain,
		arg.ServiceProvider,
		arg.TakeoverPossible,
		arg.Details,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const storeZoneTransferFinding = `-- name: StoreZoneTransferFinding :one
INSERT INTO zone_transfer_findings (domain_id,
                                    ns_record_id,
                                    severity,
                                    status,
                                    nameserver,
                                    zone_transfer_possible,
                                    transfer_type,
                                    details,
                                    transfer_details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (domain_id, nameserver)
    DO UPDATE SET ns_record_id           = $2,
                  severity               = $3,
                  status                 = $4,
                  zone_transfer_possible = $6,
                  transfer_type          = $7,
                  details                = $8,
                  transfer_details       = $9
RETURNING (xmax = 0)::boolean AS inserted
`

type StoreZoneTransferFindingParams struct {
	DomainID             pgtype.Int4     `json:"domain_id"`
	NsRecordID           pgtype.Int4     `json:"ns_record_id"`
	Severity             FindingSeverity `json:"severity"`
	Status               FindingStatus   `json:"status"`
	Nameserver           string          `json:"nameserver"`
	ZoneTransferPossible bool            `json:"zone_transfer_possible"`
	TransferType         TransferType    `json:"transfer_type"`
	Details              pgtype.Text     `json:"details"`
	TransferDetails      []byte          `json:"transfer_details"`
}

func (q *Queries) StoreZoneTransferFinding(ctx context.Context, arg StoreZoneTransferFindingParams) (bool, error) {
	row := q.db.QueryRow(ctx, storeZoneTransferFinding,
		arg.DomainID,
		arg.NsRecordID,
		arg.Severity,
		arg.Status,
		arg.Nameserver,
		arg.ZoneTransferPossible,
		arg.TransferType,
		arg.Details,
		arg.TransferDetails,
	)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const tenantFindingStatsAll = `-- name: TenantFindingStatsAll :many
SELECT
    agg.tenant_id AS tenant_id,
    COUNT(*) FILTER (WHERE sev_rank <= 2)::int AS critical_count,
    COUNT(*) FILTER (WHERE sev_rank BETWEEN 3 AND 4)::int AS warning_count
FROM (
    SELECT d.tenant_id, d.id,
        MIN(CASE f.severity
            WHEN 'critical' THEN 1
            WHEN 'high'     THEN 2
            WHEN 'medium'   THEN 3
            WHEN 'low'      THEN 4
            WHEN 'info'     THEN 5
            ELSE 6
        END) AS sev_rank
    FROM domains d
    JOIN (
        SELECT domain_id, severity::text AS severity, uid, 'SPF'::text AS kind, issue_type FROM spf_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'DKIM'::text, issue_type FROM dkim_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'DMARC'::text, issue_type FROM dmarc_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'ZONE'::text,
               CASE WHEN zone_transfer_possible THEN 'zone_transfer_exposed' ELSE 'zone_transfer_refused' END
            FROM zone_transfer_findings WHERE zone_transfer_possible = true
        UNION ALL
        SELECT domain_id, severity::text, uid, 'CERT'::text, issue_type FROM certificate_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'DNSSEC'::text, issue_type FROM dnssec_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'DANGLING'::text,
               CASE WHEN takeover_possible THEN 'subdomain_takeover' ELSE 'dangling_cname' END
            FROM dangling_cname_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'CNAME'::text, issue_type FROM cname_redirection_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'CAA_CONFIG'::text, issue_type FROM caa_configuration_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'CAA_COMPLIANCE'::text, issue_type FROM caa_compliance_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'MIN_RECORDS'::text, issue_type FROM minimum_record_set_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'EMAIL_COMPLIANCE'::text, issue_type FROM email_auth_compliance_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'NS_CONFIG'::text, issue_type FROM ns_configuration_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'NS_REDUNDANCY'::text, issue_type FROM nameserver_redundancy_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'NS_REACHABILITY'::text, issue_type FROM nameserver_reachability_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'NS_LATENCY'::text, 'high_latency'::text FROM dns_resolution_latency_findings WHERE status = 'open'
        UNION ALL
        SELECT domain_id, severity::text, uid, 'NS_CONSISTENCY'::text, 'resolver_mismatch'::text FROM dns_resolution_consistency_findings WHERE status = 'open'
    ) f ON f.domain_id = d.id
        AND NOT EXISTS (
            SELECT 1 FROM finding_suppressions s
            WHERE s.tenant_id = d.tenant_id
              AND (s.expires_at IS NULL OR s.expires_at > now())
              AND (s.finding_uid = f.uid
                OR (s.finding_uid IS NULL AND s.kind = f.kind AND s.issue_type = f.issue_type
                    AND (s.domain_id IS NULL OR s.domain_id = d.id)))
        )
    GROUP BY d.tenant_id, d.id
) agg
GROUP BY agg.tenant_id
`

type TenantFindingStatsAllRow struct {
	TenantID      pgtype.Int4 `json:"tenant_id"`
	CriticalCount int32       `json:"critical_count"`
	WarningCount  int32       `json:"warning_count"`
}

// Per-tenant counts of domains whose worst open finding is critical/high
// (critical_count) versus medium/low (warning_count), in a single grouped pass
// over all tenants. Runs off the request path (periodic refresh job); the result
// is cached into tenant_stats.
func (q *Queries) TenantFindingStatsAll(ctx context.Context) ([]TenantFindingStatsAllRow, error) {
	rows, err := q.db.Query(ctx, tenantFindingStatsAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantFindingStatsAllRow{}
	for rows.Next() {
		var i TenantFindingStatsAllRow
		if err := rows.Scan(&i.TenantID, &i.CriticalCount, &i.WarningCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
