// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assetsGetByDomainName = `-- name: AssetsGetByDomainName :one
SELECT id, uid, tenant_id, kind, value, parent_asset_id, is_cdn, source, first_seen, last_seen, domain_id
FROM assets
WHERE tenant_id = $1
  AND kind = 'domain'
  AND value = $2
`

type AssetsGetByDomainNameParams struct {
	TenantID int32  `json:"tenant_id"`
	Value    string `json:"value"`
}

func (q *Queries) AssetsGetByDomainName(ctx context.Context, arg AssetsGetByDomainNameParams) (Assets, error) {
	row := q.db.QueryRow(ctx, assetsGetByDomainName, arg.TenantID, arg.Value)
	var i Assets
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Kind,
		&i.Value,
		&i.ParentAssetID,
		&i.IsCdn,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.DomainID,
	)
	return i, err
}

const assetsGetByID = `-- name: AssetsGetByID :one
SELECT id, uid, tenant_id, kind, value, parent_asset_id, is_cdn, source, first_seen, last_seen, domain_id
FROM assets
WHERE id = $1
`

func (q *Queries) AssetsGetByID(ctx context.Context, id int64) (Assets, error) {
	row := q.db.QueryRow(ctx, assetsGetByID, id)
	var i Assets
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Kind,
		&i.Value,
		&i.ParentAssetID,
		&i.IsCdn,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.DomainID,
	)
	return i, err
}

const assetsUpsertDomain = `-- name: AssetsUpsertDomain :one
INSERT INTO assets (tenant_id, kind, value, source, domain_id, last_seen)
VALUES ($1, 'domain', $2, $3, $4, NOW())
ON CONFLICT (tenant_id, kind, value)
    DO UPDATE SET last_seen = NOW(), domain_id = EXCLUDED.domain_id
RETURNING id, uid, tenant_id, kind, value, parent_asset_id, is_cdn, source, first_seen, last_seen, domain_id
`

type AssetsUpsertDomainParams struct {
	TenantID int32       `json:"tenant_id"`
	Value    string      `json:"value"`
	Source   string      `json:"source"`
	DomainID pgtype.Int4 `json:"domain_id"`
}

// Ensure the asset row for a domain exists (1:1), bumping last_seen and keeping the
// domain_id FK current. Idempotent so domains created after the backfill
// self-register on their first scan; the FK re-link heals any pre-FK asset row.
func (q *Queries) AssetsUpsertDomain(ctx context.Context, arg AssetsUpsertDomainParams) (Assets, error) {
	row := q.db.QueryRow(ctx, assetsUpsertDomain,
		arg.TenantID,
		arg.Value,
		arg.Source,
		arg.DomainID,
	)
	var i Assets
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Kind,
		&i.Value,
		&i.ParentAssetID,
		&i.IsCdn,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.DomainID,
	)
	return i, err
}
