// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package store

import (
	"context"
)

const userCredentialGetByUserID = `-- name: UserCredentialGetByUserID :one
SELECT id, user_id, password_hash, created_at, updated_at
FROM user_credentials
WHERE user_id = $1
`

func (q *Queries) UserCredentialGetByUserID(ctx context.Context, userID int32) (UserCredentials, error) {
	row := q.db.QueryRow(ctx, userCredentialGetByUserID, userID)
	var i UserCredentials
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userCredentialUpsert = `-- name: UserCredentialUpsert :exec
INSERT INTO user_credentials (user_id, password_hash)
VALUES ($1, $2)
ON CONFLICT (user_id)
    DO UPDATE SET password_hash = EXCLUDED.password_hash,
                  updated_at    = NOW()
`

type UserCredentialUpsertParams struct {
	UserID       int32  `json:"user_id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UserCredentialUpsert(ctx context.Context, arg UserCredentialUpsertParams) error {
	_, err := q.db.Exec(ctx, userCredentialUpsert, arg.UserID, arg.PasswordHash)
	return err
}
