// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dns_cache.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const dNSCacheGet = `-- name: DNSCacheGet :one
SELECT answers, status, expires_at
FROM dns_cache
WHERE qtype = $1
  AND fqdn = $2
  AND expires_at > now()
`

type DNSCacheGetParams struct {
	Qtype int32  `json:"qtype"`
	Fqdn  string `json:"fqdn"`
}

type DNSCacheGetRow struct {
	Answers   []string           `json:"answers"`
	Status    int16              `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) DNSCacheGet(ctx context.Context, arg DNSCacheGetParams) (DNSCacheGetRow, error) {
	row := q.db.QueryRow(ctx, dNSCacheGet, arg.Qtype, arg.Fqdn)
	var i DNSCacheGetRow
	err := row.Scan(&i.Answers, &i.Status, &i.ExpiresAt)
	return i, err
}

const dNSCachePurgeExpired = `-- name: DNSCachePurgeExpired :execrows
DELETE FROM dns_cache
WHERE expires_at < now()
`

func (q *Queries) DNSCachePurgeExpired(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, dNSCachePurgeExpired)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dNSCacheUpsert = `-- name: DNSCacheUpsert :exec
INSERT INTO dns_cache (qtype, fqdn, answers, status, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (qtype, fqdn) DO UPDATE
    SET answers    = EXCLUDED.answers,
        status     = EXCLUDED.status,
        expires_at = EXCLUDED.expires_at
`

type DNSCacheUpsertParams struct {
	Qtype     int32              `json:"qtype"`
	Fqdn      string             `json:"fqdn"`
	Answers   []string           `json:"answers"`
	Status    int16              `json:"status"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) DNSCacheUpsert(ctx context.Context, arg DNSCacheUpsertParams) error {
	_, err := q.db.Exec(ctx, dNSCacheUpsert,
		arg.Qtype,
		arg.Fqdn,
		arg.Answers,
		arg.Status,
		arg.ExpiresAt,
	)
	return err
}

const rateLimitAcquire = `-- name: RateLimitAcquire :one
UPDATE dns_rate_limit_bucket
SET tokens      = LEAST(burst, tokens + EXTRACT(EPOCH FROM (now() - last_refill)) * rate_qps) - 1,
    last_refill = now(),
    updated_at  = now()
WHERE key = $1
  AND LEAST(burst, tokens + EXTRACT(EPOCH FROM (now() - last_refill)) * rate_qps) >= 1
RETURNING tokens
`

func (q *Queries) RateLimitAcquire(ctx context.Context, key string) (float64, error) {
	row := q.db.QueryRow(ctx, rateLimitAcquire, key)
	var tokens float64
	err := row.Scan(&tokens)
	return tokens, err
}

const rateLimitUpsertBucket = `-- name: RateLimitUpsertBucket :exec
INSERT INTO dns_rate_limit_bucket (key, tokens, rate_qps, burst)
VALUES ($1, $2, $3, $4)
ON CONFLICT (key) DO NOTHING
`

type RateLimitUpsertBucketParams struct {
	Key     string  `json:"key"`
	Tokens  float64 `json:"tokens"`
	RateQps float64 `json:"rate_qps"`
	Burst   float64 `json:"burst"`
}

func (q *Queries) RateLimitUpsertBucket(ctx context.Context, arg RateLimitUpsertBucketParams) error {
	_, err := q.db.Exec(ctx, rateLimitUpsertBucket,
		arg.Key,
		arg.Tokens,
		arg.RateQps,
		arg.Burst,
	)
	return err
}
