// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const domainsCreate = `-- name: DomainsCreate :one
INSERT INTO domains (tenant_id, name, domain_type, source, status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (tenant_id, name)
    DO UPDATE SET updated_at = NOW()
RETURNING id, uid, name, domain_type, source, status, created_at, updated_at
`

type DomainsCreateParams struct {
	TenantID   pgtype.Int4  `json:"tenant_id"`
	Name       string       `json:"name"`
	DomainType DomainType   `json:"domain_type"`
	Source     DomainSource `json:"source"`
	Status     DomainStatus `json:"status"`
}

type DomainsCreateRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	Name       string             `json:"name"`
	DomainType DomainType         `json:"domain_type"`
	Source     DomainSource       `json:"source"`
	Status     DomainStatus       `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Create a new domain (no auth)
func (q *Queries) DomainsCreate(ctx context.Context, arg DomainsCreateParams) (DomainsCreateRow, error) {
	row := q.db.QueryRow(ctx, domainsCreate,
		arg.TenantID,
		arg.Name,
		arg.DomainType,
		arg.Source,
		arg.Status,
	)
	var i DomainsCreateRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Name,
		&i.DomainType,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainsDeleteByID = `-- name: DomainsDeleteByID :one
DELETE
FROM domains
WHERE uid = $1
  AND tenant_id = $2
RETURNING id, uid, tenant_id, name, domain_type, source, status, created_at, updated_at
`

type DomainsDeleteByIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

type DomainsDeleteByIDRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	TenantID   pgtype.Int4        `json:"tenant_id"`
	Name       string             `json:"name"`
	DomainType DomainType         `json:"domain_type"`
	Source     DomainSource       `json:"source"`
	Status     DomainStatus       `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Delete a domain (no auth)
func (q *Queries) DomainsDeleteByID(ctx context.Context, arg DomainsDeleteByIDParams) (DomainsDeleteByIDRow, error) {
	row := q.db.QueryRow(ctx, domainsDeleteByID, arg.Uid, arg.TenantID)
	var i DomainsDeleteByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Name,
		&i.DomainType,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainsDeleteCount = `-- name: DomainsDeleteCount :one
WITH RECURSIVE domain_tree AS (
    -- Base case: the domain we're deleting
    SELECT d.id, d.uid, d.name
    FROM domains d
    WHERE d.uid = $1
      AND d.tenant_id = $2

    UNION ALL

    -- Recursive case: all child domains
    SELECT d.id, d.uid, d.name
    FROM domains d
             JOIN domain_tree dt ON d.parent_domain_id = dt.id)
SELECT COUNT(*)
FROM domain_tree
`

type DomainsDeleteCountParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

func (q *Queries) DomainsDeleteCount(ctx context.Context, arg DomainsDeleteCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, domainsDeleteCount, arg.Uid, arg.TenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const domainsGetAllRecordsByTenantID = `-- name: DomainsGetAllRecordsByTenantID :many
SELECT d.name,
       a.ipv4_address,
       aaaa.ipv6_address,
       mx.preference      AS mx_pref,
       mx.target          AS mx_target,
       txt.value          AS txt_record,
       ptr.target         AS ptr_target,
       cname.target       AS cname_target,
       ns.nameserver,
       soa.nameserver     AS soa_nameserver,
       soa.email          AS soa_email,
       soa.serial         AS soa_serial,
       soa.refresh        AS soa_refresh,
       soa.retry          AS soa_retry,
       soa.expire         AS soa_expire,
       soa.minimum_ttl    AS soa_minimum_ttl,
       srv.target         AS srv_target,
       srv.port           AS srv_port,
       srv.weight         AS srv_weight,
       srv.priority       AS srv_priority,
       caa.flags          AS caa_flags,
       caa.tag            AS caa_tag,
       caa.value          AS caa_value,
       dnskey.public_key  AS dnskey_public_key,
       dnskey.flags       AS dnskey_flags,
       dnskey.protocol    AS dnskey_protocol,
       dnskey.algorithm   AS dnskey_algorithm,
       ds.key_tag         AS ds_keytag,
       ds.algorithm       AS ds_algorithm,
       ds.digest_type     AS ds_digest_type,
       ds.digest          AS ds_digest,
       rrsig.type_covered AS rrsig_type_covered,
       rrsig.algorithm    AS rrsig_algorithm,
       rrsig.labels       AS rrsig_labels,
       rrsig.original_ttl AS rrsig_original_ttl,
       rrsig.expiration   AS rrsig_expiration,
       rrsig.inception    AS rrsig_inception,
       rrsig.key_tag      AS rrsig_keytag,
       rrsig.signer_name  AS rrsig_signer_name,
       rrsig.signature    AS rrsig_signature
FROM domains d
         LEFT JOIN a_records a ON d.id = a.domain_id
         LEFT JOIN aaaa_records aaaa ON d.id = aaaa.domain_id
         LEFT JOIN mx_records mx ON d.id = mx.domain_id
         LEFT JOIN txt_records txt ON d.id = txt.domain_id
         LEFT JOIN ptr_records ptr ON d.id = ptr.domain_id
         LEFT JOIN cname_records cname ON d.id = cname.domain_id
         LEFT JOIN ns_records ns ON d.id = ns.domain_id
         LEFT JOIN soa_records soa ON d.id = soa.domain_id
         LEFT JOIN srv_records srv ON d.id = srv.domain_id
         LEFT JOIN caa_records caa ON d.id = caa.domain_id
         LEFT JOIN dnskey_records dnskey ON d.id = dnskey.domain_id
         LEFT JOIN ds_records ds ON d.id = ds.domain_id
         LEFT JOIN rrsig_records rrsig ON d.id = rrsig.domain_id
WHERE d.tenant_id = $1
ORDER BY d.name ASC
LIMIT $2 OFFSET $3
`

type DomainsGetAllRecordsByTenantIDParams struct {
	TenantID pgtype.Int4 `json:"tenant_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

type DomainsGetAllRecordsByTenantIDRow struct {
	Name             string      `json:"name"`
	Ipv4Address      pgtype.Text `json:"ipv4_address"`
	Ipv6Address      pgtype.Text `json:"ipv6_address"`
	MxPref           pgtype.Int4 `json:"mx_pref"`
	MxTarget         pgtype.Text `json:"mx_target"`
	TxtRecord        pgtype.Text `json:"txt_record"`
	PtrTarget        pgtype.Text `json:"ptr_target"`
	CnameTarget      pgtype.Text `json:"cname_target"`
	Nameserver       pgtype.Text `json:"nameserver"`
	SoaNameserver    pgtype.Text `json:"soa_nameserver"`
	SoaEmail         pgtype.Text `json:"soa_email"`
	SoaSerial        pgtype.Int8 `json:"soa_serial"`
	SoaRefresh       pgtype.Int4 `json:"soa_refresh"`
	SoaRetry         pgtype.Int4 `json:"soa_retry"`
	SoaExpire        pgtype.Int4 `json:"soa_expire"`
	SoaMinimumTtl    pgtype.Int4 `json:"soa_minimum_ttl"`
	SrvTarget        pgtype.Text `json:"srv_target"`
	SrvPort          pgtype.Int4 `json:"srv_port"`
	SrvWeight        pgtype.Int4 `json:"srv_weight"`
	SrvPriority      pgtype.Int4 `json:"srv_priority"`
	CaaFlags         pgtype.Int4 `json:"caa_flags"`
	CaaTag           pgtype.Text `json:"caa_tag"`
	CaaValue         pgtype.Text `json:"caa_value"`
	DnskeyPublicKey  pgtype.Text `json:"dnskey_public_key"`
	DnskeyFlags      pgtype.Int4 `json:"dnskey_flags"`
	DnskeyProtocol   pgtype.Int4 `json:"dnskey_protocol"`
	DnskeyAlgorithm  pgtype.Int4 `json:"dnskey_algorithm"`
	DsKeytag         pgtype.Int4 `json:"ds_keytag"`
	DsAlgorithm      pgtype.Int4 `json:"ds_algorithm"`
	DsDigestType     pgtype.Int4 `json:"ds_digest_type"`
	DsDigest         pgtype.Text `json:"ds_digest"`
	RrsigTypeCovered pgtype.Int4 `json:"rrsig_type_covered"`
	RrsigAlgorithm   pgtype.Int4 `json:"rrsig_algorithm"`
	RrsigLabels      pgtype.Int4 `json:"rrsig_labels"`
	RrsigOriginalTtl pgtype.Int4 `json:"rrsig_original_ttl"`
	RrsigExpiration  pgtype.Int4 `json:"rrsig_expiration"`
	RrsigInception   pgtype.Int4 `json:"rrsig_inception"`
	RrsigKeytag      pgtype.Int4 `json:"rrsig_keytag"`
	RrsigSignerName  pgtype.Text `json:"rrsig_signer_name"`
	RrsigSignature   pgtype.Text `json:"rrsig_signature"`
}

// Get domains with all their DNS records
// todo: develop only; reconsider need for this
func (q *Queries) DomainsGetAllRecordsByTenantID(ctx context.Context, arg DomainsGetAllRecordsByTenantIDParams) ([]DomainsGetAllRecordsByTenantIDRow, error) {
	rows, err := q.db.Query(ctx, domainsGetAllRecordsByTenantID, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainsGetAllRecordsByTenantIDRow{}
	for rows.Next() {
		var i DomainsGetAllRecordsByTenantIDRow
		if err := rows.Scan(
			&i.Name,
			&i.Ipv4Address,
			&i.Ipv6Address,
			&i.MxPref,
			&i.MxTarget,
			&i.TxtRecord,
			&i.PtrTarget,
			&i.CnameTarget,
			&i.Nameserver,
			&i.SoaNameserver,
			&i.SoaEmail,
			&i.SoaSerial,
			&i.SoaRefresh,
			&i.SoaRetry,
			&i.SoaExpire,
			&i.SoaMinimumTtl,
			&i.SrvTarget,
			&i.SrvPort,
			&i.SrvWeight,
			&i.SrvPriority,
			&i.CaaFlags,
			&i.CaaTag,
			&i.CaaValue,
			&i.DnskeyPublicKey,
			&i.DnskeyFlags,
			&i.DnskeyProtocol,
			&i.DnskeyAlgorithm,
			&i.DsKeytag,
			&i.DsAlgorithm,
			&i.DsDigestType,
			&i.DsDigest,
			&i.RrsigTypeCovered,
			&i.RrsigAlgorithm,
			&i.RrsigLabels,
			&i.RrsigOriginalTtl,
			&i.RrsigExpiration,
			&i.RrsigInception,
			&i.RrsigKeytag,
			&i.RrsigSignerName,
			&i.RrsigSignature,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainsGetByDomainID = `-- name: DomainsGetByDomainID :one
SELECT id, uid, tenant_id, name
FROM domains
WHERE id = $1
`

type DomainsGetByDomainIDRow struct {
	ID       int32       `json:"id"`
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
	Name     string      `json:"name"`
}

// Read a domain by its internal id (no auth). Used to rebuild a domain identity
// for an observation from a stored foreign key (e.g. a suppression's domain_id).
func (q *Queries) DomainsGetByDomainID(ctx context.Context, id int32) (DomainsGetByDomainIDRow, error) {
	row := q.db.QueryRow(ctx, domainsGetByDomainID, id)
	var i DomainsGetByDomainIDRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Name,
	)
	return i, err
}

const domainsGetByID = `-- name: DomainsGetByID :one
SELECT id,
       uid,
       tenant_id,
       name,
       domain_type,
       source,
       status,
       scan_frequency,
       next_scan_at,
       last_scanned_at,
       created_at,
       updated_at
FROM domains
WHERE uid = $1
  AND tenant_id = $2
`

type DomainsGetByIDParams struct {
	Uid      string      `json:"uid"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

type DomainsGetByIDRow struct {
	ID            int32              `json:"id"`
	Uid           string             `json:"uid"`
	TenantID      pgtype.Int4        `json:"tenant_id"`
	Name          string             `json:"name"`
	DomainType    DomainType         `json:"domain_type"`
	Source        DomainSource       `json:"source"`
	Status        DomainStatus       `json:"status"`
	ScanFrequency NullScanFrequency  `json:"scan_frequency"`
	NextScanAt    pgtype.Timestamptz `json:"next_scan_at"`
	LastScannedAt pgtype.Timestamptz `json:"last_scanned_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) DomainsGetByID(ctx context.Context, arg DomainsGetByIDParams) (DomainsGetByIDRow, error) {
	row := q.db.QueryRow(ctx, domainsGetByID, arg.Uid, arg.TenantID)
	var i DomainsGetByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Name,
		&i.DomainType,
		&i.Source,
		&i.Status,
		&i.ScanFrequency,
		&i.NextScanAt,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainsGetByIdentifier = `-- name: DomainsGetByIdentifier :one
SELECT id,
       uid,
       tenant_id,
       name,
       domain_type,
       source,
       status,
       created_at,
       updated_at
FROM domains
WHERE tenant_id = $1
  AND (id = $2 OR uid = $3 OR name = $4)
LIMIT 1
`

type DomainsGetByIdentifierParams struct {
	TenantID pgtype.Int4 `json:"tenant_id"`
	ID       int32       `json:"id"`
	Uid      string      `json:"uid"`
	Name     string      `json:"name"`
}

type DomainsGetByIdentifierRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	TenantID   pgtype.Int4        `json:"tenant_id"`
	Name       string             `json:"name"`
	DomainType DomainType         `json:"domain_type"`
	Source     DomainSource       `json:"source"`
	Status     DomainStatus       `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Read a domain by ID, UID, or name and tenant ID (no auth)
func (q *Queries) DomainsGetByIdentifier(ctx context.Context, arg DomainsGetByIdentifierParams) (DomainsGetByIdentifierRow, error) {
	row := q.db.QueryRow(ctx, domainsGetByIdentifier,
		arg.TenantID,
		arg.ID,
		arg.Uid,
		arg.Name,
	)
	var i DomainsGetByIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Name,
		&i.DomainType,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainsGetByName = `-- name: DomainsGetByName :one
SELECT id,
       uid,
       tenant_id,
       name,
       domain_type,
       source,
       status,
       created_at,
       updated_at
FROM domains
WHERE tenant_id = $1
  AND name = $2
`

type DomainsGetByNameParams struct {
	TenantID pgtype.Int4 `json:"tenant_id"`
	Name     string      `json:"name"`
}

type DomainsGetByNameRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	TenantID   pgtype.Int4        `json:"tenant_id"`
	Name       string             `json:"name"`
	DomainType DomainType         `json:"domain_type"`
	Source     DomainSource       `json:"source"`
	Status     DomainStatus       `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Read a domain by name and tenant ID (no auth)
func (q *Queries) DomainsGetByName(ctx context.Context, arg DomainsGetByNameParams) (DomainsGetByNameRow, error) {
	row := q.db.QueryRow(ctx, domainsGetByName, arg.TenantID, arg.Name)
	var i DomainsGetByNameRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Name,
		&i.DomainType,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainsGetScanFrequencies = `-- name: DomainsGetScanFrequencies :one
SELECT d.scan_frequency,
       COALESCE(ts.default_scan_frequency, 'daily')::scan_frequency AS default_scan_frequency
FROM domains d
         LEFT JOIN tenant_settings ts ON ts.tenant_id = d.tenant_id
WHERE d.id = $1
`

type DomainsGetScanFrequenciesRow struct {
	ScanFrequency        NullScanFrequency `json:"scan_frequency"`
	DefaultScanFrequency ScanFrequency     `json:"default_scan_frequency"`
}

// Resolve a domain's scheduling inputs in one read: its own override (NULL =
// inherit) and its tenant's default. EnqueueDomainScan's chokepoint uses this to
// compute the effective frequency. Falls back to 'daily' when the tenant has no
// settings row yet (brand-new tenant before its first settings write).
func (q *Queries) DomainsGetScanFrequencies(ctx context.Context, domainID int32) (DomainsGetScanFrequenciesRow, error) {
	row := q.db.QueryRow(ctx, domainsGetScanFrequencies, domainID)
	var i DomainsGetScanFrequenciesRow
	err := row.Scan(&i.ScanFrequency, &i.DefaultScanFrequency)
	return i, err
}

const domainsIDsByTenantID = `-- name: DomainsIDsByTenantID :many
SELECT id
FROM domains
WHERE tenant_id = $1
`

// All domain IDs owned by a tenant. Used by the per-tenant stats refresh to
// drive the index-driven record/finding aggregates; returns no rows when the
// tenant has no domains (the caller then caches zeros).
func (q *Queries) DomainsIDsByTenantID(ctx context.Context, tenantID pgtype.Int4) ([]int32, error) {
	rows, err := q.db.Query(ctx, domainsIDsByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var id int32
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainsInsert = `-- name: DomainsInsert :one
INSERT INTO domains (tenant_id, name, domain_type, source, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, uid, name, domain_type, source, status, created_at, updated_at
`

type DomainsInsertParams struct {
	TenantID   pgtype.Int4  `json:"tenant_id"`
	Name       string       `json:"name"`
	DomainType DomainType   `json:"domain_type"`
	Source     DomainSource `json:"source"`
	Status     DomainStatus `json:"status"`
}

type DomainsInsertRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	Name       string             `json:"name"`
	DomainType DomainType         `json:"domain_type"`
	Source     DomainSource       `json:"source"`
	Status     DomainStatus       `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Insert-only create for the POST path. Unlike DomainsCreate (an upsert used by
// enumeration), a duplicate (tenant_id, name) raises a unique-violation the
// handler maps to 409 — so a duplicate POST never silently becomes a rescan.
func (q *Queries) DomainsInsert(ctx context.Context, arg DomainsInsertParams) (DomainsInsertRow, error) {
	row := q.db.QueryRow(ctx, domainsInsert,
		arg.TenantID,
		arg.Name,
		arg.DomainType,
		arg.Source,
		arg.Status,
	)
	var i DomainsInsertRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.Name,
		&i.DomainType,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainsList = `-- name: DomainsList :many
SELECT id,
       uid,
       tenant_id,
       name,
       domain_type,
       source,
       status,
       last_scanned_at,
       next_scan_at,
       created_at,
       updated_at,
       count(*) OVER () AS total_count
FROM domains
WHERE tenant_id = $1
  AND ($2::text IS NULL OR name ILIKE '%' || $2 || '%')
  AND ($3::domain_source IS NULL OR source = $3)
  AND ($4::domain_type IS NULL OR domain_type = $4)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type DomainsListParams struct {
	TenantID   pgtype.Int4      `json:"tenant_id"`
	Name       pgtype.Text      `json:"name"`
	Source     NullDomainSource `json:"source"`
	DomainType NullDomainType   `json:"domain_type"`
	PageOffset int32            `json:"page_offset"`
	PageLimit  int32            `json:"page_limit"`
}

type DomainsListRow struct {
	ID            int32              `json:"id"`
	Uid           string             `json:"uid"`
	TenantID      pgtype.Int4        `json:"tenant_id"`
	Name          string             `json:"name"`
	DomainType    DomainType         `json:"domain_type"`
	Source        DomainSource       `json:"source"`
	Status        DomainStatus       `json:"status"`
	LastScannedAt pgtype.Timestamptz `json:"last_scanned_at"`
	NextScanAt    pgtype.Timestamptz `json:"next_scan_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	TotalCount    int64              `json:"total_count"`
}

// Tenant-scoped page of domains with optional name/source/domain_type filters.
// Each filter is independently optional via narg (NULL = "no filter"), collapsing
// the former DomainsListByTenantID + DomainsSearchByName into one query. tenant_id
// stays the leading predicate so the multi-tenancy boundary is preserved; the
// source/type equality filters are sargable (idx_domains_source/idx_domains_type)
// and strictly cheaper than the non-sargable leading-wildcard name ILIKE.
// total_count is the window count over the FILTERED set, for pagination.
func (q *Queries) DomainsList(ctx context.Context, arg DomainsListParams) ([]DomainsListRow, error) {
	rows, err := q.db.Query(ctx, domainsList,
		arg.TenantID,
		arg.Name,
		arg.Source,
		arg.DomainType,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainsListRow{}
	for rows.Next() {
		var i DomainsListRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.Name,
			&i.DomainType,
			&i.Source,
			&i.Status,
			&i.LastScannedAt,
			&i.NextScanAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainsListDueForScan = `-- name: DomainsListDueForScan :many
SELECT d.id,
       d.uid,
       d.tenant_id,
       d.name,
       d.status,
       COALESCE(d.scan_frequency, ts.default_scan_frequency, 'daily')::scan_frequency AS effective_frequency
FROM domains d
         LEFT JOIN tenant_settings ts ON ts.tenant_id = d.tenant_id
WHERE d.status = 'active'
  AND d.next_scan_at IS NOT NULL
  AND d.next_scan_at <= now()
ORDER BY d.next_scan_at ASC
LIMIT $1
`

type DomainsListDueForScanRow struct {
	ID                 int32         `json:"id"`
	Uid                string        `json:"uid"`
	TenantID           pgtype.Int4   `json:"tenant_id"`
	Name               string        `json:"name"`
	Status             DomainStatus  `json:"status"`
	EffectiveFrequency ScanFrequency `json:"effective_frequency"`
}

// The scheduler's hot query: active domains whose scheduling cursor has come due,
// oldest-due first, capped at @batch_limit so a burst of simultaneously-due
// domains can't thunder-herd queue_scanner (the rest stay due for the next tick).
// Rides the partial index idx_domains_next_scan_at. Returns the effective
// frequency (own override ?? tenant default) so the caller sets a matching recency
// window. 'off' domains have a NULL cursor and are excluded by the index.
func (q *Queries) DomainsListDueForScan(ctx context.Context, batchLimit int32) ([]DomainsListDueForScanRow, error) {
	rows, err := q.db.Query(ctx, domainsListDueForScan, batchLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainsListDueForScanRow{}
	for rows.Next() {
		var i DomainsListDueForScanRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.Name,
			&i.Status,
			&i.EffectiveFrequency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const domainsMarkScanned = `-- name: DomainsMarkScanned :exec
UPDATE domains
SET last_scanned_at = now(),
    next_scan_at    = CASE
                          WHEN $1::boolean THEN NULL
                          ELSE now()
                              + make_interval(secs => $2::double precision)
                              + make_interval(secs => $2::double precision * random() * 0.10)
        END
WHERE id = $3
`

type DomainsMarkScannedParams struct {
	IsOff    bool    `json:"is_off"`
	BaseSecs float64 `json:"base_secs"`
	DomainID int32   `json:"domain_id"`
}

// The single chokepoint stamp, called from EnqueueDomainScan after a scan row is
// created — so it fires on EVERY trigger (manual, scheduled, discovered). Stamps
// the real last-scan time and advances the scheduling cursor by the effective
// interval with ±10% jitter to de-herd a same-tick batch. @is_off true => the
// cursor is cleared (NULL) so the domain falls out of the schedule.
func (q *Queries) DomainsMarkScanned(ctx context.Context, arg DomainsMarkScannedParams) error {
	_, err := q.db.Exec(ctx, domainsMarkScanned, arg.IsOff, arg.BaseSecs, arg.DomainID)
	return err
}

const domainsRecomputeNextScanByTenantDefault = `-- name: DomainsRecomputeNextScanByTenantDefault :exec
UPDATE domains
SET next_scan_at = CASE
                       WHEN $1::boolean THEN NULL
                       ELSE now()
                           + make_interval(secs => $2::double precision)
                           + make_interval(secs => $2::double precision * random() * 0.10)
    END
WHERE tenant_id = $3
  AND scan_frequency IS NULL
  AND status = 'active'
`

type DomainsRecomputeNextScanByTenantDefaultParams struct {
	IsOff    bool        `json:"is_off"`
	BaseSecs float64     `json:"base_secs"`
	TenantID pgtype.Int4 `json:"tenant_id"`
}

// Bulk-recompute next_scan_at for a tenant's inheriting domains (no override)
// after its default changes. Overridden domains (scan_frequency NOT NULL) are
// untouched; inactive domains are skipped (they re-enter via the due path on
// reactivation). Bounded to one tenant + active rows; re-jitters per row so a bulk
// default change can't herd. @is_off true => those domains are paused (cursor NULL).
func (q *Queries) DomainsRecomputeNextScanByTenantDefault(ctx context.Context, arg DomainsRecomputeNextScanByTenantDefaultParams) error {
	_, err := q.db.Exec(ctx, domainsRecomputeNextScanByTenantDefault, arg.IsOff, arg.BaseSecs, arg.TenantID)
	return err
}

const domainsSetScanFrequency = `-- name: DomainsSetScanFrequency :one
UPDATE domains
SET scan_frequency = $1,
    next_scan_at   = CASE
                         WHEN $2::boolean THEN NULL
                         ELSE now()
                             + make_interval(secs => $3::double precision)
                             + make_interval(secs => $3::double precision * random() * 0.10)
        END
WHERE uid = $4
  AND tenant_id = $5
RETURNING id, uid, tenant_id, name, domain_type, source, status, scan_frequency,
    next_scan_at, last_scanned_at, created_at, updated_at
`

type DomainsSetScanFrequencyParams struct {
	ScanFrequency NullScanFrequency `json:"scan_frequency"`
	IsOff         bool              `json:"is_off"`
	BaseSecs      float64           `json:"base_secs"`
	Uid           string            `json:"uid"`
	TenantID      pgtype.Int4       `json:"tenant_id"`
}

type DomainsSetScanFrequencyRow struct {
	ID            int32              `json:"id"`
	Uid           string             `json:"uid"`
	TenantID      pgtype.Int4        `json:"tenant_id"`
	Name          string             `json:"name"`
	DomainType    DomainType         `json:"domain_type"`
	Source        DomainSource       `json:"source"`
	Status        DomainStatus       `json:"status"`
	ScanFrequency NullScanFrequency  `json:"scan_frequency"`
	NextScanAt    pgtype.Timestamptz `json:"next_scan_at"`
	LastScannedAt pgtype.Timestamptz `json:"last_scanned_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

// Set a domain's per-domain override (NULL = inherit the tenant default) and
// recompute its scheduling cursor from the supplied effective interval (±10%
// jitter). @is_off true => cursor NULL (paused). Tenant-scoped by uid + tenant_id.
func (q *Queries) DomainsSetScanFrequency(ctx context.Context, arg DomainsSetScanFrequencyParams) (DomainsSetScanFrequencyRow, error) {
	row := q.db.QueryRow(ctx, domainsSetScanFrequency,
		arg.ScanFrequency,
		arg.IsOff,
		arg.BaseSecs,
		arg.Uid,
		arg.TenantID,
	)
	var i DomainsSetScanFrequencyRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Name,
		&i.DomainType,
		&i.Source,
		&i.Status,
		&i.ScanFrequency,
		&i.NextScanAt,
		&i.LastScannedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainsUpdateByID = `-- name: DomainsUpdateByID :one
UPDATE domains
SET status      = $2,
    domain_type = $3,
    source      = $4
WHERE uid = $1
  AND tenant_id = $5
RETURNING id, uid, tenant_id, name, domain_type, source, status, created_at, updated_at
`

type DomainsUpdateByIDParams struct {
	Uid        string       `json:"uid"`
	Status     DomainStatus `json:"status"`
	DomainType DomainType   `json:"domain_type"`
	Source     DomainSource `json:"source"`
	TenantID   pgtype.Int4  `json:"tenant_id"`
}

type DomainsUpdateByIDRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	TenantID   pgtype.Int4        `json:"tenant_id"`
	Name       string             `json:"name"`
	DomainType DomainType         `json:"domain_type"`
	Source     DomainSource       `json:"source"`
	Status     DomainStatus       `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Update a domain's status (no auth)
func (q *Queries) DomainsUpdateByID(ctx context.Context, arg DomainsUpdateByIDParams) (DomainsUpdateByIDRow, error) {
	row := q.db.QueryRow(ctx, domainsUpdateByID,
		arg.Uid,
		arg.Status,
		arg.DomainType,
		arg.Source,
		arg.TenantID,
	)
	var i DomainsUpdateByIDRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Name,
		&i.DomainType,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const domainsUpdateByIDTypeSource = `-- name: DomainsUpdateByIDTypeSource :one
UPDATE domains
SET domain_type = $2,
    source      = $3
WHERE uid = $1
  AND tenant_id = $4
RETURNING id, uid, tenant_id, name, domain_type, source, status, created_at, updated_at
`

type DomainsUpdateByIDTypeSourceParams struct {
	Uid        string       `json:"uid"`
	DomainType DomainType   `json:"domain_type"`
	Source     DomainSource `json:"source"`
	TenantID   pgtype.Int4  `json:"tenant_id"`
}

type DomainsUpdateByIDTypeSourceRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	TenantID   pgtype.Int4        `json:"tenant_id"`
	Name       string             `json:"name"`
	DomainType DomainType         `json:"domain_type"`
	Source     DomainSource       `json:"source"`
	Status     DomainStatus       `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Update a domain's type and source (no auth)
func (q *Queries) DomainsUpdateByIDTypeSource(ctx context.Context, arg DomainsUpdateByIDTypeSourceParams) (DomainsUpdateByIDTypeSourceRow, error) {
	row := q.db.QueryRow(ctx, domainsUpdateByIDTypeSource,
		arg.Uid,
		arg.DomainType,
		arg.Source,
		arg.TenantID,
	)
	var i DomainsUpdateByIDTypeSourceRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Name,
		&i.DomainType,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
