// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings_read.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findingsListByDomainUID = `-- name: FindingsListByDomainUID :many

SELECT f.id, f.uid, f.tenant_id, f.asset_id, f.check_kind, f.issue_type, f.entity_key, f.severity, f.status, f.title, f.details, f.evidence, f.first_seen, f.last_seen, f.resolved_at
FROM findings f
         JOIN assets a ON a.id = f.asset_id AND a.kind = 'domain'
         JOIN domains d ON d.id = a.domain_id
WHERE d.uid = $1
  AND f.tenant_id = $2
  AND f.status = 'open'
ORDER BY CASE f.severity
             WHEN 'critical' THEN 1
             WHEN 'high' THEN 2
             WHEN 'medium' THEN 3
             WHEN 'low' THEN 4
             WHEN 'info' THEN 5
             ELSE 6
             END ASC,
         f.first_seen ASC
`

type FindingsListByDomainUIDParams struct {
	Uid      string `json:"uid"`
	TenantID int32  `json:"tenant_id"`
}

// Generic finding readers, sourced from the single `findings` table (replacing
// the 19 typed per-check tables). A finding's domain is resolved via
// findings.asset_id -> assets (kind='domain') -> domains (assets.domain_id = d.id):
// a lifecycle FK, not the reusable name, so a deleted-then-recreated domain never
// inherits the prior domain's findings. Tenant isolation is enforced directly on
// findings.tenant_id, which is denormalized onto the row at write time.
// Every open finding for one domain (identified by its uid, scoped to the
// caller's tenant), worst-first.
func (q *Queries) FindingsListByDomainUID(ctx context.Context, arg FindingsListByDomainUIDParams) ([]Findings, error) {
	rows, err := q.db.Query(ctx, findingsListByDomainUID, arg.Uid, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Findings{}
	for rows.Next() {
		var i Findings
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.AssetID,
			&i.CheckKind,
			&i.IssueType,
			&i.EntityKey,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Details,
			&i.Evidence,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findingsListTenantOpen = `-- name: FindingsListTenantOpen :many
SELECT f.uid        AS finding_uid,
       f.check_kind,
       f.issue_type,
       f.entity_key,
       f.severity,
       f.status,
       f.title,
       f.details,
       f.evidence,
       f.first_seen,
       d.uid         AS domain_uid,
       d.name        AS domain_name
FROM findings f
         JOIN assets a ON a.id = f.asset_id AND a.kind = 'domain'
         JOIN domains d ON d.id = a.domain_id
WHERE f.tenant_id = $1
  AND f.status = 'open'
ORDER BY d.name ASC,
         CASE f.severity
             WHEN 'critical' THEN 1
             WHEN 'high' THEN 2
             WHEN 'medium' THEN 3
             WHEN 'low' THEN 4
             WHEN 'info' THEN 5
             ELSE 6
             END ASC,
         f.first_seen ASC
`

type FindingsListTenantOpenRow struct {
	FindingUid string             `json:"finding_uid"`
	CheckKind  string             `json:"check_kind"`
	IssueType  string             `json:"issue_type"`
	EntityKey  string             `json:"entity_key"`
	Severity   string             `json:"severity"`
	Status     string             `json:"status"`
	Title      string             `json:"title"`
	Details    string             `json:"details"`
	Evidence   []byte             `json:"evidence"`
	FirstSeen  pgtype.Timestamptz `json:"first_seen"`
	DomainUid  string             `json:"domain_uid"`
	DomainName string             `json:"domain_name"`
}

// Every open finding across a tenant's domains, ordered domain-then-severity so
// the caller can group consecutively without a second sort. Severity/kind/domain
// filtering is applied in Go (buildTenantFindings) rather than here. Named
// distinctly from assessors.sql's (soon-to-be-deleted) FindingsListByTenant.
func (q *Queries) FindingsListTenantOpen(ctx context.Context, tenantID int32) ([]FindingsListTenantOpenRow, error) {
	rows, err := q.db.Query(ctx, findingsListTenantOpen, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingsListTenantOpenRow{}
	for rows.Next() {
		var i FindingsListTenantOpenRow
		if err := rows.Scan(
			&i.FindingUid,
			&i.CheckKind,
			&i.IssueType,
			&i.EntityKey,
			&i.Severity,
			&i.Status,
			&i.Title,
			&i.Details,
			&i.Evidence,
			&i.FirstSeen,
			&i.DomainUid,
			&i.DomainName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findingsSummaryByDomainIDs = `-- name: FindingsSummaryByDomainIDs :many
WITH ids AS (SELECT unnest($1::int[]) AS domain_id),
     open_findings AS (SELECT d.id AS domain_id, f.severity
                        FROM findings f
                                 JOIN assets a ON a.id = f.asset_id AND a.kind = 'domain'
                                 JOIN domains d ON d.id = a.domain_id
                        WHERE f.status = 'open'
                          AND d.id = ANY ($1::int[]))
SELECT ids.domain_id::int                    AS domain_id,
       MIN(CASE ofd.severity
               WHEN 'critical' THEN 1
               WHEN 'high' THEN 2
               WHEN 'medium' THEN 3
               WHEN 'low' THEN 4
               WHEN 'info' THEN 5
               ELSE 6
           END)::int                         AS severity_rank,
       COUNT(ofd.severity)::int              AS finding_count
FROM ids
         LEFT JOIN open_findings ofd ON ofd.domain_id = ids.domain_id
GROUP BY ids.domain_id
`

type FindingsSummaryByDomainIDsRow struct {
	DomainID     int32 `json:"domain_id"`
	SeverityRank int32 `json:"severity_rank"`
	FindingCount int32 `json:"finding_count"`
}

// Worst open-finding severity + count per domain, for a page of domain IDs (no
// N+1). severity_rank: critical=1 high=2 medium=3 low=4 info=5 none=6. Feeds the
// Domains list/detail row badges (DomainsService.FindingsSummaryForPage).
func (q *Queries) FindingsSummaryByDomainIDs(ctx context.Context, domainIds []int32) ([]FindingsSummaryByDomainIDsRow, error) {
	rows, err := q.db.Query(ctx, findingsSummaryByDomainIDs, domainIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingsSummaryByDomainIDsRow{}
	for rows.Next() {
		var i FindingsSummaryByDomainIDsRow
		if err := rows.Scan(&i.DomainID, &i.SeverityRank, &i.FindingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findingsTenantStats = `-- name: FindingsTenantStats :many
WITH per_domain AS (SELECT f.tenant_id,
                            f.asset_id,
                            MIN(CASE f.severity
                                    WHEN 'critical' THEN 1
                                    WHEN 'high' THEN 2
                                    WHEN 'medium' THEN 3
                                    WHEN 'low' THEN 4
                                    WHEN 'info' THEN 5
                                    ELSE 6
                                END) AS sev_rank,
                            COUNT(*) AS finding_count
                     FROM findings f
                              JOIN assets a ON a.id = f.asset_id AND a.kind = 'domain'
                              JOIN domains d ON d.id = a.domain_id
                     WHERE f.status = 'open'
                       AND ($1::int IS NULL OR f.tenant_id = $1)
                     GROUP BY f.tenant_id, f.asset_id)
SELECT tenant_id,
       COUNT(*) FILTER (WHERE sev_rank <= 2)::int            AS critical_count,
       COUNT(*) FILTER (WHERE sev_rank BETWEEN 3 AND 4)::int AS warning_count,
       SUM(finding_count)::int                               AS open_total,
       COUNT(*)::int                                         AS domain_count
FROM per_domain
GROUP BY tenant_id
`

type FindingsTenantStatsRow struct {
	TenantID      int32 `json:"tenant_id"`
	CriticalCount int32 `json:"critical_count"`
	WarningCount  int32 `json:"warning_count"`
	OpenTotal     int32 `json:"open_total"`
	DomainCount   int32 `json:"domain_count"`
}

// Per-tenant rollup of open findings: domains whose worst open finding is
// critical/high (critical_count) vs medium/low (warning_count), the total open
// finding count, and the distinct domain count with at least one open finding.
// tenant_id narrows to a single tenant; NULL rolls up every tenant in one pass
// (the periodic all-fleet refresh). Joined through assets/domains on the
// assets.domain_id FK so a finding whose domain was deleted (the FK cascade removes
// its asset + findings) never appears.
func (q *Queries) FindingsTenantStats(ctx context.Context, tenantID pgtype.Int4) ([]FindingsTenantStatsRow, error) {
	rows, err := q.db.Query(ctx, findingsTenantStats, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingsTenantStatsRow{}
	for rows.Next() {
		var i FindingsTenantStatsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.CriticalCount,
			&i.WarningCount,
			&i.OpenTotal,
			&i.DomainCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
