// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: findings.sql

package store

import (
	"context"
)

const findingsEventInsert = `-- name: FindingsEventInsert :exec
INSERT INTO findings_events (finding_id, event)
VALUES ($1, $2)
`

type FindingsEventInsertParams struct {
	FindingID int64  `json:"finding_id"`
	Event     string `json:"event"`
}

func (q *Queries) FindingsEventInsert(ctx context.Context, arg FindingsEventInsertParams) error {
	_, err := q.db.Exec(ctx, findingsEventInsert, arg.FindingID, arg.Event)
	return err
}

const findingsListOpenByAssetCheck = `-- name: FindingsListOpenByAssetCheck :many
SELECT id, issue_type, entity_key
FROM findings
WHERE asset_id = $1
  AND check_kind = $2
  AND status = 'open'
`

type FindingsListOpenByAssetCheckParams struct {
	AssetID   int64  `json:"asset_id"`
	CheckKind string `json:"check_kind"`
}

type FindingsListOpenByAssetCheckRow struct {
	ID        int64  `json:"id"`
	IssueType string `json:"issue_type"`
	EntityKey string `json:"entity_key"`
}

// The open findings for one asset+check, used to compute which became absent.
func (q *Queries) FindingsListOpenByAssetCheck(ctx context.Context, arg FindingsListOpenByAssetCheckParams) ([]FindingsListOpenByAssetCheckRow, error) {
	rows, err := q.db.Query(ctx, findingsListOpenByAssetCheck, arg.AssetID, arg.CheckKind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindingsListOpenByAssetCheckRow{}
	for rows.Next() {
		var i FindingsListOpenByAssetCheckRow
		if err := rows.Scan(&i.ID, &i.IssueType, &i.EntityKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findingsLockScope = `-- name: FindingsLockScope :exec
SELECT pg_advisory_xact_lock(
               hashtextextended($1::text, $2::bigint))
`

type FindingsLockScopeParams struct {
	CheckKind string `json:"check_kind"`
	AssetID   int64  `json:"asset_id"`
}

// Serialize one asset/check scope within the caller's transaction.
func (q *Queries) FindingsLockScope(ctx context.Context, arg FindingsLockScopeParams) error {
	_, err := q.db.Exec(ctx, findingsLockScope, arg.CheckKind, arg.AssetID)
	return err
}

const findingsResolve = `-- name: FindingsResolve :exec
UPDATE findings
SET status      = 'resolved',
    resolved_at = NOW()
WHERE id = $1
  AND status = 'open'
`

func (q *Queries) FindingsResolve(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, findingsResolve, id)
	return err
}

const findingsUpsert = `-- name: FindingsUpsert :one
WITH prior AS (SELECT status
               FROM findings
               WHERE tenant_id = $1
                 AND asset_id = $2
                 AND check_kind = $3
                 AND issue_type = $4
                 AND entity_key = $5)
INSERT INTO findings (tenant_id, asset_id, check_kind, issue_type, entity_key, severity, title, details, evidence)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (tenant_id, asset_id, check_kind, issue_type, entity_key)
    DO UPDATE SET severity    = EXCLUDED.severity,
                  title       = EXCLUDED.title,
                  details     = EXCLUDED.details,
                  evidence    = EXCLUDED.evidence,
                  status      = 'open',
                  resolved_at = NULL,
                  last_seen   = NOW()
RETURNING id, COALESCE((SELECT status FROM prior), '')::text AS prior_status
`

type FindingsUpsertParams struct {
	TenantID  int32  `json:"tenant_id"`
	AssetID   int64  `json:"asset_id"`
	CheckKind string `json:"check_kind"`
	IssueType string `json:"issue_type"`
	EntityKey string `json:"entity_key"`
	Severity  string `json:"severity"`
	Title     string `json:"title"`
	Details   string `json:"details"`
	Evidence  []byte `json:"evidence"`
}

type FindingsUpsertRow struct {
	ID          int64  `json:"id"`
	PriorStatus string `json:"prior_status"`
}

// Return the prior status for lifecycle events. Reopening preserves first_seen.
func (q *Queries) FindingsUpsert(ctx context.Context, arg FindingsUpsertParams) (FindingsUpsertRow, error) {
	row := q.db.QueryRow(ctx, findingsUpsert,
		arg.TenantID,
		arg.AssetID,
		arg.CheckKind,
		arg.IssueType,
		arg.EntityKey,
		arg.Severity,
		arg.Title,
		arg.Details,
		arg.Evidence,
	)
	var i FindingsUpsertRow
	err := row.Scan(&i.ID, &i.PriorStatus)
	return i, err
}
