// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invitations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const invitationCreate = `-- name: InvitationCreate :one
INSERT INTO invitations (tenant_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uid, tenant_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type InvitationCreateParams struct {
	TenantID  int32              `json:"tenant_id"`
	Email     string             `json:"email"`
	Role      UserRole           `json:"role"`
	TokenHash string             `json:"token_hash"`
	InvitedBy pgtype.Int4        `json:"invited_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InvitationCreate(ctx context.Context, arg InvitationCreateParams) (Invitations, error) {
	row := q.db.QueryRow(ctx, invitationCreate,
		arg.TenantID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i Invitations
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invitationExpiredDelete = `-- name: InvitationExpiredDelete :exec
DELETE
FROM invitations
WHERE tenant_id = $1
  AND email = $2
  AND accepted_at IS NULL
  AND expires_at <= NOW()
`

type InvitationExpiredDeleteParams struct {
	TenantID int32  `json:"tenant_id"`
	Email    string `json:"email"`
}

// Clear any stale expired-but-unaccepted invite for (tenant, email) so it does not
// wedge the partial unique index when re-inviting.
func (q *Queries) InvitationExpiredDelete(ctx context.Context, arg InvitationExpiredDeleteParams) error {
	_, err := q.db.Exec(ctx, invitationExpiredDelete, arg.TenantID, arg.Email)
	return err
}

const invitationGetByTokenHash = `-- name: InvitationGetByTokenHash :one
SELECT id, uid, tenant_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
FROM invitations
WHERE token_hash = $1
  AND accepted_at IS NULL
  AND expires_at > NOW()
`

// Only returns live, open invites; expired/accepted/revoked (deleted) ones are
// uniformly rejected as not-found.
func (q *Queries) InvitationGetByTokenHash(ctx context.Context, tokenHash string) (Invitations, error) {
	row := q.db.QueryRow(ctx, invitationGetByTokenHash, tokenHash)
	var i Invitations
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invitationMarkAccepted = `-- name: InvitationMarkAccepted :exec
UPDATE invitations
SET accepted_at = NOW()
WHERE id = $1
`

func (q *Queries) InvitationMarkAccepted(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, invitationMarkAccepted, id)
	return err
}

const invitationRevoke = `-- name: InvitationRevoke :one
DELETE
FROM invitations
WHERE uid = $1
  AND tenant_id = $2
  AND accepted_at IS NULL
RETURNING id, uid, tenant_id, email
`

type InvitationRevokeParams struct {
	Uid      string `json:"uid"`
	TenantID int32  `json:"tenant_id"`
}

type InvitationRevokeRow struct {
	ID       int32  `json:"id"`
	Uid      string `json:"uid"`
	TenantID int32  `json:"tenant_id"`
	Email    string `json:"email"`
}

// Hard delete: a revoked invite ceases to exist (no revoked_at column needed).
func (q *Queries) InvitationRevoke(ctx context.Context, arg InvitationRevokeParams) (InvitationRevokeRow, error) {
	row := q.db.QueryRow(ctx, invitationRevoke, arg.Uid, arg.TenantID)
	var i InvitationRevokeRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.Email,
	)
	return i, err
}

const invitationsListByTenant = `-- name: InvitationsListByTenant :many
SELECT id, uid, tenant_id, email, role, invited_by, expires_at, accepted_at, created_at
FROM invitations
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type InvitationsListByTenantRow struct {
	ID         int32              `json:"id"`
	Uid        string             `json:"uid"`
	TenantID   int32              `json:"tenant_id"`
	Email      string             `json:"email"`
	Role       UserRole           `json:"role"`
	InvitedBy  pgtype.Int4        `json:"invited_by"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InvitationsListByTenant(ctx context.Context, tenantID int32) ([]InvitationsListByTenantRow, error) {
	rows, err := q.db.Query(ctx, invitationsListByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InvitationsListByTenantRow{}
	for rows.Next() {
		var i InvitationsListByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
