// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: observations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireDomainScanLock = `-- name: AcquireDomainScanLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Transaction-scoped advisory lock keyed on domain_id. Serializes concurrent
// scan enqueues for the same domain so the recency-check-then-enqueue is atomic
// (auto-released at commit/rollback; no phantom-row gap like FOR UPDATE).
func (q *Queries) AcquireDomainScanLock(ctx context.Context, dollar_1 int64) error {
	_, err := q.db.Exec(ctx, acquireDomainScanLock, dollar_1)
	return err
}

const notifyDomainObservation = `-- name: NotifyDomainObservation :exec
SELECT pg_notify('domain_observations', $1::text)
`

// Fire a LISTEN/NOTIFY signal that an observation was written for a domain. The
// server process LISTENs on 'domain_observations' and fans the change out to
// browser SSE streams. Called on the observation transaction's connection, so
// the signal is delivered on COMMIT and dropped on ROLLBACK — subscribers never
// observe uncommitted state. Delivery is best-effort: a listener that is down
// when this fires misses the event (the DB stays source of truth).
func (q *Queries) NotifyDomainObservation(ctx context.Context, payload string) error {
	_, err := q.db.Exec(ctx, notifyDomainObservation, payload)
	return err
}

const observationsCreate = `-- name: ObservationsCreate :one
INSERT INTO domain_observations (tenant_id, domain_id, domain_uid, domain_name, scan_id, entity_type, entity_key,
                                 change_type, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, domain_id, domain_uid, domain_name, scan_id, entity_type, entity_key, change_type, payload, observed_at
`

type ObservationsCreateParams struct {
	TenantID   int32       `json:"tenant_id"`
	DomainID   pgtype.Int4 `json:"domain_id"`
	DomainUid  string      `json:"domain_uid"`
	DomainName string      `json:"domain_name"`
	ScanID     pgtype.Int8 `json:"scan_id"`
	EntityType string      `json:"entity_type"`
	EntityKey  string      `json:"entity_key"`
	ChangeType string      `json:"change_type"`
	Payload    []byte      `json:"payload"`
}

// Append one change to the observation log.
func (q *Queries) ObservationsCreate(ctx context.Context, arg ObservationsCreateParams) (DomainObservations, error) {
	row := q.db.QueryRow(ctx, observationsCreate,
		arg.TenantID,
		arg.DomainID,
		arg.DomainUid,
		arg.DomainName,
		arg.ScanID,
		arg.EntityType,
		arg.EntityKey,
		arg.ChangeType,
		arg.Payload,
	)
	var i DomainObservations
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DomainID,
		&i.DomainUid,
		&i.DomainName,
		&i.ScanID,
		&i.EntityType,
		&i.EntityKey,
		&i.ChangeType,
		&i.Payload,
		&i.ObservedAt,
	)
	return i, err
}

const observationsCreateIfChanged = `-- name: ObservationsCreateIfChanged :one
WITH latest AS (
    SELECT payload
    FROM domain_observations
    WHERE tenant_id = $1
      AND domain_name = $2
      AND entity_type = $3
      AND entity_key = $4
    ORDER BY observed_at DESC, id DESC
    LIMIT 1
)
INSERT INTO domain_observations (tenant_id, domain_id, domain_uid, domain_name, scan_id,
                                 entity_type, entity_key, change_type, payload)
SELECT $1, $5, $6, $2, $7, $3, $4,
       CASE WHEN NOT EXISTS (SELECT 1 FROM latest) THEN 'created' ELSE 'updated' END,
       $8::jsonb
WHERE NOT EXISTS (SELECT 1 FROM latest WHERE latest.payload = $8::jsonb)
RETURNING id, tenant_id, domain_id, domain_uid, domain_name, scan_id, entity_type, entity_key, change_type, payload, observed_at
`

type ObservationsCreateIfChangedParams struct {
	TenantID   int32       `json:"tenant_id"`
	DomainName string      `json:"domain_name"`
	EntityType string      `json:"entity_type"`
	EntityKey  string      `json:"entity_key"`
	DomainID   pgtype.Int4 `json:"domain_id"`
	DomainUid  string      `json:"domain_uid"`
	ScanID     pgtype.Int8 `json:"scan_id"`
	Payload    []byte      `json:"payload"`
}

// Append one change to the observation log, but only when the payload differs
// from the most-recent prior observation for the same entity. Unchanged
// re-observations insert nothing (the query returns no rows -> pgx.ErrNoRows,
// which the caller treats as "suppressed"). change_type is 'created' on first
// sighting, 'updated' otherwise. JSONB equality is value-level, so it is robust
// to key ordering between the stored payload and the new one.
func (q *Queries) ObservationsCreateIfChanged(ctx context.Context, arg ObservationsCreateIfChangedParams) (DomainObservations, error) {
	row := q.db.QueryRow(ctx, observationsCreateIfChanged,
		arg.TenantID,
		arg.DomainName,
		arg.EntityType,
		arg.EntityKey,
		arg.DomainID,
		arg.DomainUid,
		arg.ScanID,
		arg.Payload,
	)
	var i DomainObservations
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DomainID,
		&i.DomainUid,
		&i.DomainName,
		&i.ScanID,
		&i.EntityType,
		&i.EntityKey,
		&i.ChangeType,
		&i.Payload,
		&i.ObservedAt,
	)
	return i, err
}

const observationsListByScan = `-- name: ObservationsListByScan :many
SELECT id, tenant_id, domain_id, domain_uid, domain_name, scan_id, entity_type, entity_key, change_type, payload, observed_at
FROM domain_observations
WHERE scan_id = $1
  AND tenant_id = $2
ORDER BY entity_type, entity_key
`

type ObservationsListByScanParams struct {
	ScanID   pgtype.Int8 `json:"scan_id"`
	TenantID int32       `json:"tenant_id"`
}

// All observations emitted during a single scan (scan-diff detail), tenant-scoped
// for defense-in-depth even though callers verify scan ownership first.
func (q *Queries) ObservationsListByScan(ctx context.Context, arg ObservationsListByScanParams) ([]DomainObservations, error) {
	rows, err := q.db.Query(ctx, observationsListByScan, arg.ScanID, arg.TenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainObservations{}
	for rows.Next() {
		var i DomainObservations
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ScanID,
			&i.EntityType,
			&i.EntityKey,
			&i.ChangeType,
			&i.Payload,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationsListByTenantDomainName = `-- name: ObservationsListByTenantDomainName :many
SELECT id, tenant_id, domain_id, domain_uid, domain_name, scan_id, entity_type, entity_key, change_type, payload, observed_at
FROM domain_observations
WHERE tenant_id = $1
  AND domain_name = $2
ORDER BY observed_at DESC
`

type ObservationsListByTenantDomainNameParams struct {
	TenantID   int32  `json:"tenant_id"`
	DomainName string `json:"domain_name"`
}

// Timeline for a (tenant, domain name). Keyed on (tenant_id, domain_name) so a
// re-added domain shows its prior timeline and a deleted domain stays reachable.
func (q *Queries) ObservationsListByTenantDomainName(ctx context.Context, arg ObservationsListByTenantDomainNameParams) ([]DomainObservations, error) {
	rows, err := q.db.Query(ctx, observationsListByTenantDomainName, arg.TenantID, arg.DomainName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainObservations{}
	for rows.Next() {
		var i DomainObservations
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ScanID,
			&i.EntityType,
			&i.EntityKey,
			&i.ChangeType,
			&i.Payload,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationsListTimelineByTenantDomainName = `-- name: ObservationsListTimelineByTenantDomainName :many
SELECT o.id, o.tenant_id, o.domain_id, o.domain_uid, o.domain_name, o.scan_id,
       o.entity_type, o.entity_key, o.change_type, o.payload, o.observed_at,
       s.uid        AS scan_uid,
       s.source     AS scan_source,
       s.started_at AS scan_started_at,
       p.uid        AS parent_scan_uid
FROM domain_observations o
         JOIN scans s ON s.id = o.scan_id
         LEFT JOIN scans p ON p.id = s.parent_scan_id
WHERE o.tenant_id = $1
  AND o.domain_name = $2
ORDER BY s.started_at DESC, s.id DESC, o.id ASC
`

type ObservationsListTimelineByTenantDomainNameParams struct {
	TenantID   int32  `json:"tenant_id"`
	DomainName string `json:"domain_name"`
}

type ObservationsListTimelineByTenantDomainNameRow struct {
	ID            int64              `json:"id"`
	TenantID      int32              `json:"tenant_id"`
	DomainID      pgtype.Int4        `json:"domain_id"`
	DomainUid     string             `json:"domain_uid"`
	DomainName    string             `json:"domain_name"`
	ScanID        pgtype.Int8        `json:"scan_id"`
	EntityType    string             `json:"entity_type"`
	EntityKey     string             `json:"entity_key"`
	ChangeType    string             `json:"change_type"`
	Payload       []byte             `json:"payload"`
	ObservedAt    pgtype.Timestamptz `json:"observed_at"`
	ScanUid       string             `json:"scan_uid"`
	ScanSource    DomainSource       `json:"scan_source"`
	ScanStartedAt pgtype.Timestamptz `json:"scan_started_at"`
	ParentScanUid pgtype.Text        `json:"parent_scan_uid"`
}

// One-shot timeline: every observation for a (tenant, domain name) joined to its
// scan (uid, source, started_at) and the scan's parent uid. The INNER JOIN to
// scans means scans that recorded no changes never appear — the timeline is a
// pure change history. Ordered newest-scan-first; callers group rows by scan uid.
func (q *Queries) ObservationsListTimelineByTenantDomainName(ctx context.Context, arg ObservationsListTimelineByTenantDomainNameParams) ([]ObservationsListTimelineByTenantDomainNameRow, error) {
	rows, err := q.db.Query(ctx, observationsListTimelineByTenantDomainName, arg.TenantID, arg.DomainName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationsListTimelineByTenantDomainNameRow{}
	for rows.Next() {
		var i ObservationsListTimelineByTenantDomainNameRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ScanID,
			&i.EntityType,
			&i.EntityKey,
			&i.ChangeType,
			&i.Payload,
			&i.ObservedAt,
			&i.ScanUid,
			&i.ScanSource,
			&i.ScanStartedAt,
			&i.ParentScanUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationsListWithScanUIDByTenantDomainName = `-- name: ObservationsListWithScanUIDByTenantDomainName :many
SELECT o.id, o.tenant_id, o.domain_id, o.domain_uid, o.domain_name, o.scan_id,
       o.entity_type, o.entity_key, o.change_type, o.payload, o.observed_at,
       s.uid AS scan_uid
FROM domain_observations o
         LEFT JOIN scans s ON s.id = o.scan_id
WHERE o.tenant_id = $1
  AND o.domain_name = $2
ORDER BY o.observed_at DESC
`

type ObservationsListWithScanUIDByTenantDomainNameParams struct {
	TenantID   int32  `json:"tenant_id"`
	DomainName string `json:"domain_name"`
}

type ObservationsListWithScanUIDByTenantDomainNameRow struct {
	ID         int64              `json:"id"`
	TenantID   int32              `json:"tenant_id"`
	DomainID   pgtype.Int4        `json:"domain_id"`
	DomainUid  string             `json:"domain_uid"`
	DomainName string             `json:"domain_name"`
	ScanID     pgtype.Int8        `json:"scan_id"`
	EntityType string             `json:"entity_type"`
	EntityKey  string             `json:"entity_key"`
	ChangeType string             `json:"change_type"`
	Payload    []byte             `json:"payload"`
	ObservedAt pgtype.Timestamptz `json:"observed_at"`
	ScanUid    pgtype.Text        `json:"scan_uid"`
}

// Flat timeline for a (tenant, domain name) with each observation's scan uid
// joined in, so the records-history API exposes scan_uid (never the numeric id)
// without an N+1. LEFT JOIN keeps observations whose scan was detached (NULL).
func (q *Queries) ObservationsListWithScanUIDByTenantDomainName(ctx context.Context, arg ObservationsListWithScanUIDByTenantDomainNameParams) ([]ObservationsListWithScanUIDByTenantDomainNameRow, error) {
	rows, err := q.db.Query(ctx, observationsListWithScanUIDByTenantDomainName, arg.TenantID, arg.DomainName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationsListWithScanUIDByTenantDomainNameRow{}
	for rows.Next() {
		var i ObservationsListWithScanUIDByTenantDomainNameRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ScanID,
			&i.EntityType,
			&i.EntityKey,
			&i.ChangeType,
			&i.Payload,
			&i.ObservedAt,
			&i.ScanUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scansCreate = `-- name: ScansCreate :one
INSERT INTO scans (tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uid, tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source, started_at
`

type ScansCreateParams struct {
	TenantID     int32        `json:"tenant_id"`
	DomainID     pgtype.Int4  `json:"domain_id"`
	DomainUid    string       `json:"domain_uid"`
	DomainName   string       `json:"domain_name"`
	ParentScanID pgtype.Int8  `json:"parent_scan_id"`
	Source       DomainSource `json:"source"`
}

// Create a scan correlation row. Scans group every observation emitted during a
// single domain scan so the timeline can diff scan N vs N+1.
func (q *Queries) ScansCreate(ctx context.Context, arg ScansCreateParams) (Scans, error) {
	row := q.db.QueryRow(ctx, scansCreate,
		arg.TenantID,
		arg.DomainID,
		arg.DomainUid,
		arg.DomainName,
		arg.ParentScanID,
		arg.Source,
	)
	var i Scans
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.DomainID,
		&i.DomainUid,
		&i.DomainName,
		&i.ParentScanID,
		&i.Source,
		&i.StartedAt,
	)
	return i, err
}

const scansGetByTenantUID = `-- name: ScansGetByTenantUID :one
WITH target_scan AS (
    SELECT s.id, s.uid, s.domain_uid, s.domain_name, s.source,
           s.started_at, s.parent_scan_id
    FROM scans s
    WHERE s.tenant_id = $1
      AND s.uid = $2
),
change_counts AS (
    SELECT o.scan_id, o.entity_type, o.change_type, count(*) AS n
    FROM domain_observations o
    WHERE o.scan_id IN (SELECT id FROM target_scan)
    GROUP BY o.scan_id, o.entity_type, o.change_type
),
per_scan AS (
    SELECT scan_id,
           COALESCE(sum(n) FILTER (WHERE change_type = 'created'), 0) AS created,
           COALESCE(sum(n) FILTER (WHERE change_type = 'updated'), 0) AS updated,
           COALESCE(sum(n) FILTER (WHERE change_type = 'deleted'), 0) AS deleted,
           jsonb_agg(jsonb_build_object(
               'entity_type', entity_type,
               'change_type', change_type,
               'count', n) ORDER BY entity_type, change_type) AS breakdown
    FROM change_counts
    GROUP BY scan_id
)
SELECT t.id                           AS scan_id,
       t.uid                          AS scan_uid,
       t.domain_uid,
       t.domain_name,
       t.source,
       t.started_at,
       p.uid                          AS parent_scan_uid,
       COALESCE(ps.created, 0)::int   AS created_count,
       COALESCE(ps.updated, 0)::int   AS updated_count,
       COALESCE(ps.deleted, 0)::int   AS deleted_count,
       COALESCE(ps.breakdown, '[]'::jsonb) AS breakdown
FROM target_scan t
         LEFT JOIN scans p ON p.id = t.parent_scan_id
         LEFT JOIN per_scan ps ON ps.scan_id = t.id
`

type ScansGetByTenantUIDParams struct {
	TenantID int32  `json:"tenant_id"`
	Uid      string `json:"uid"`
}

type ScansGetByTenantUIDRow struct {
	ScanID        int64              `json:"scan_id"`
	ScanUid       string             `json:"scan_uid"`
	DomainUid     string             `json:"domain_uid"`
	DomainName    string             `json:"domain_name"`
	Source        DomainSource       `json:"source"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	ParentScanUid pgtype.Text        `json:"parent_scan_uid"`
	CreatedCount  int32              `json:"created_count"`
	UpdatedCount  int32              `json:"updated_count"`
	DeletedCount  int32              `json:"deleted_count"`
	Breakdown     []byte             `json:"breakdown"`
}

// Single scan by (tenant_id, uid) with its per-scan change aggregate, for the
// scan-detail API. The (tenant_id, uid) WHERE gate is the isolation boundary: a
// cross-tenant or unknown uid returns no rows (pgx.ErrNoRows). Mirrors the
// aggregate columns of ScansListByTenant and additionally returns the internal
// scan id so the caller can fetch this scan's observations. Observation
// aggregation is bounded to the single target scan and rides idx_obs_scan.
func (q *Queries) ScansGetByTenantUID(ctx context.Context, arg ScansGetByTenantUIDParams) (ScansGetByTenantUIDRow, error) {
	row := q.db.QueryRow(ctx, scansGetByTenantUID, arg.TenantID, arg.Uid)
	var i ScansGetByTenantUIDRow
	err := row.Scan(
		&i.ScanID,
		&i.ScanUid,
		&i.DomainUid,
		&i.DomainName,
		&i.Source,
		&i.StartedAt,
		&i.ParentScanUid,
		&i.CreatedCount,
		&i.UpdatedCount,
		&i.DeletedCount,
		&i.Breakdown,
	)
	return i, err
}

const scansGetRecentByTenantDomainName = `-- name: ScansGetRecentByTenantDomainName :one
SELECT id, uid, tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source, started_at
FROM scans
WHERE tenant_id = $1
  AND domain_name = $2
ORDER BY started_at DESC
LIMIT 1
`

type ScansGetRecentByTenantDomainNameParams struct {
	TenantID   int32  `json:"tenant_id"`
	DomainName string `json:"domain_name"`
}

// Most recent scan for a (tenant, domain name). Backs the recency guard that
// dedupes discovered scans. Keyed on (tenant_id, domain_name), not domain_id,
// so it survives a domain delete/re-add.
func (q *Queries) ScansGetRecentByTenantDomainName(ctx context.Context, arg ScansGetRecentByTenantDomainNameParams) (Scans, error) {
	row := q.db.QueryRow(ctx, scansGetRecentByTenantDomainName, arg.TenantID, arg.DomainName)
	var i Scans
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.DomainID,
		&i.DomainUid,
		&i.DomainName,
		&i.ParentScanID,
		&i.Source,
		&i.StartedAt,
	)
	return i, err
}

const scansListByParent = `-- name: ScansListByParent :many
SELECT id, uid, tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source, started_at
FROM scans
WHERE parent_scan_id = $1
ORDER BY started_at DESC, id DESC
`

// Child scans of an apex scan (lineage). Lets the timeline group discovered
// child scans under the scan that found them.
func (q *Queries) ScansListByParent(ctx context.Context, parentScanID pgtype.Int8) ([]Scans, error) {
	rows, err := q.db.Query(ctx, scansListByParent, parentScanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scans{}
	for rows.Next() {
		var i Scans
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ParentScanID,
			&i.Source,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scansListByTenant = `-- name: ScansListByTenant :many
WITH target_scans AS (
    SELECT s.id, s.uid, s.domain_uid, s.domain_name, s.source,
           s.started_at, s.parent_scan_id
    FROM scans s
    WHERE s.tenant_id = $1
      AND ($2::timestamptz IS NULL
           OR s.started_at >= $2)
    ORDER BY s.started_at DESC, s.id DESC
    LIMIT $3
),
change_counts AS (
    SELECT o.scan_id, o.entity_type, o.change_type, count(*) AS n
    FROM domain_observations o
    WHERE o.scan_id IN (SELECT id FROM target_scans)
    GROUP BY o.scan_id, o.entity_type, o.change_type
),
per_scan AS (
    SELECT scan_id,
           COALESCE(sum(n) FILTER (WHERE change_type = 'created'), 0) AS created,
           COALESCE(sum(n) FILTER (WHERE change_type = 'updated'), 0) AS updated,
           COALESCE(sum(n) FILTER (WHERE change_type = 'deleted'), 0) AS deleted,
           jsonb_agg(jsonb_build_object(
               'entity_type', entity_type,
               'change_type', change_type,
               'count', n) ORDER BY entity_type, change_type) AS breakdown
    FROM change_counts
    GROUP BY scan_id
)
SELECT t.uid                          AS scan_uid,
       t.domain_uid,
       t.domain_name,
       t.source,
       t.started_at,
       p.uid                          AS parent_scan_uid,
       COALESCE(ps.created, 0)::int   AS created_count,
       COALESCE(ps.updated, 0)::int   AS updated_count,
       COALESCE(ps.deleted, 0)::int   AS deleted_count,
       COALESCE(ps.breakdown, '[]'::jsonb) AS breakdown
FROM target_scans t
         LEFT JOIN scans p ON p.id = t.parent_scan_id
         LEFT JOIN per_scan ps ON ps.scan_id = t.id
ORDER BY t.started_at DESC, t.id DESC
`

type ScansListByTenantParams struct {
	TenantID int32              `json:"tenant_id"`
	Since    pgtype.Timestamptz `json:"since"`
	RowLimit int32              `json:"row_limit"`
}

type ScansListByTenantRow struct {
	ScanUid       string             `json:"scan_uid"`
	DomainUid     string             `json:"domain_uid"`
	DomainName    string             `json:"domain_name"`
	Source        DomainSource       `json:"source"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	ParentScanUid pgtype.Text        `json:"parent_scan_uid"`
	CreatedCount  int32              `json:"created_count"`
	UpdatedCount  int32              `json:"updated_count"`
	DeletedCount  int32              `json:"deleted_count"`
	Breakdown     []byte             `json:"breakdown"`
}

// Tenant-wide reverse-chronological scan feed with per-scan change aggregates.
// Observation aggregation is bounded to the windowed page (target_scans, capped
// by @row_limit) so it never full-scans a growing domain_observations: the
// change_counts CTE keys on scan_id from target_scans and rides idx_obs_scan.
// Clean scans (no observations) survive via LEFT JOIN per_scan -> all-zero counts
// + '[]' breakdown. Baseline scans (parent_scan_id IS NULL) yield a NULL
// parent_scan_uid. @since is nullable: NULL means all-time.
func (q *Queries) ScansListByTenant(ctx context.Context, arg ScansListByTenantParams) ([]ScansListByTenantRow, error) {
	rows, err := q.db.Query(ctx, scansListByTenant, arg.TenantID, arg.Since, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScansListByTenantRow{}
	for rows.Next() {
		var i ScansListByTenantRow
		if err := rows.Scan(
			&i.ScanUid,
			&i.DomainUid,
			&i.DomainName,
			&i.Source,
			&i.StartedAt,
			&i.ParentScanUid,
			&i.CreatedCount,
			&i.UpdatedCount,
			&i.DeletedCount,
			&i.Breakdown,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scansListByTenantDomainName = `-- name: ScansListByTenantDomainName :many
SELECT id, uid, tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source, started_at
FROM scans
WHERE tenant_id = $1
  AND domain_name = $2
ORDER BY started_at DESC, id DESC
`

type ScansListByTenantDomainNameParams struct {
	TenantID   int32  `json:"tenant_id"`
	DomainName string `json:"domain_name"`
}

// All scans for a (tenant, domain name), newest first.
func (q *Queries) ScansListByTenantDomainName(ctx context.Context, arg ScansListByTenantDomainNameParams) ([]Scans, error) {
	rows, err := q.db.Query(ctx, scansListByTenantDomainName, arg.TenantID, arg.DomainName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scans{}
	for rows.Next() {
		var i Scans
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ParentScanID,
			&i.Source,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
