// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: observations.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireDomainScanLock = `-- name: AcquireDomainScanLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

// Transaction-scoped advisory lock keyed on domain_id. Serializes concurrent
// scan enqueues for the same domain so the recency-check-then-enqueue is atomic
// (auto-released at commit/rollback; no phantom-row gap like FOR UPDATE).
func (q *Queries) AcquireDomainScanLock(ctx context.Context, dollar_1 int64) error {
	_, err := q.db.Exec(ctx, acquireDomainScanLock, dollar_1)
	return err
}

const observationsCreate = `-- name: ObservationsCreate :one
INSERT INTO domain_observations (tenant_id, domain_id, domain_uid, domain_name, scan_id, entity_type, entity_key,
                                 change_type, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, tenant_id, domain_id, domain_uid, domain_name, scan_id, entity_type, entity_key, change_type, payload, observed_at
`

type ObservationsCreateParams struct {
	TenantID   int32       `json:"tenant_id"`
	DomainID   pgtype.Int4 `json:"domain_id"`
	DomainUid  string      `json:"domain_uid"`
	DomainName string      `json:"domain_name"`
	ScanID     pgtype.Int8 `json:"scan_id"`
	EntityType string      `json:"entity_type"`
	EntityKey  string      `json:"entity_key"`
	ChangeType string      `json:"change_type"`
	Payload    []byte      `json:"payload"`
}

// Append one change to the observation log.
func (q *Queries) ObservationsCreate(ctx context.Context, arg ObservationsCreateParams) (DomainObservations, error) {
	row := q.db.QueryRow(ctx, observationsCreate,
		arg.TenantID,
		arg.DomainID,
		arg.DomainUid,
		arg.DomainName,
		arg.ScanID,
		arg.EntityType,
		arg.EntityKey,
		arg.ChangeType,
		arg.Payload,
	)
	var i DomainObservations
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.DomainID,
		&i.DomainUid,
		&i.DomainName,
		&i.ScanID,
		&i.EntityType,
		&i.EntityKey,
		&i.ChangeType,
		&i.Payload,
		&i.ObservedAt,
	)
	return i, err
}

const observationsListByScan = `-- name: ObservationsListByScan :many
SELECT id, tenant_id, domain_id, domain_uid, domain_name, scan_id, entity_type, entity_key, change_type, payload, observed_at
FROM domain_observations
WHERE scan_id = $1
ORDER BY entity_type, entity_key
`

// All observations emitted during a single scan (scan-diff feature).
func (q *Queries) ObservationsListByScan(ctx context.Context, scanID pgtype.Int8) ([]DomainObservations, error) {
	rows, err := q.db.Query(ctx, observationsListByScan, scanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainObservations{}
	for rows.Next() {
		var i DomainObservations
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ScanID,
			&i.EntityType,
			&i.EntityKey,
			&i.ChangeType,
			&i.Payload,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationsListByTenantDomainName = `-- name: ObservationsListByTenantDomainName :many
SELECT id, tenant_id, domain_id, domain_uid, domain_name, scan_id, entity_type, entity_key, change_type, payload, observed_at
FROM domain_observations
WHERE tenant_id = $1
  AND domain_name = $2
ORDER BY observed_at DESC
`

type ObservationsListByTenantDomainNameParams struct {
	TenantID   int32  `json:"tenant_id"`
	DomainName string `json:"domain_name"`
}

// Timeline for a (tenant, domain name). Keyed on (tenant_id, domain_name) so a
// re-added domain shows its prior timeline and a deleted domain stays reachable.
func (q *Queries) ObservationsListByTenantDomainName(ctx context.Context, arg ObservationsListByTenantDomainNameParams) ([]DomainObservations, error) {
	rows, err := q.db.Query(ctx, observationsListByTenantDomainName, arg.TenantID, arg.DomainName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DomainObservations{}
	for rows.Next() {
		var i DomainObservations
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ScanID,
			&i.EntityType,
			&i.EntityKey,
			&i.ChangeType,
			&i.Payload,
			&i.ObservedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scansCreate = `-- name: ScansCreate :one
INSERT INTO scans (tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, uid, tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source, started_at
`

type ScansCreateParams struct {
	TenantID     int32        `json:"tenant_id"`
	DomainID     pgtype.Int4  `json:"domain_id"`
	DomainUid    string       `json:"domain_uid"`
	DomainName   string       `json:"domain_name"`
	ParentScanID pgtype.Int8  `json:"parent_scan_id"`
	Source       DomainSource `json:"source"`
}

// Create a scan correlation row. Scans group every observation emitted during a
// single domain scan so the timeline can diff scan N vs N+1.
func (q *Queries) ScansCreate(ctx context.Context, arg ScansCreateParams) (Scans, error) {
	row := q.db.QueryRow(ctx, scansCreate,
		arg.TenantID,
		arg.DomainID,
		arg.DomainUid,
		arg.DomainName,
		arg.ParentScanID,
		arg.Source,
	)
	var i Scans
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.DomainID,
		&i.DomainUid,
		&i.DomainName,
		&i.ParentScanID,
		&i.Source,
		&i.StartedAt,
	)
	return i, err
}

const scansGetRecentByTenantDomainName = `-- name: ScansGetRecentByTenantDomainName :one
SELECT id, uid, tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source, started_at
FROM scans
WHERE tenant_id = $1
  AND domain_name = $2
ORDER BY started_at DESC
LIMIT 1
`

type ScansGetRecentByTenantDomainNameParams struct {
	TenantID   int32  `json:"tenant_id"`
	DomainName string `json:"domain_name"`
}

// Most recent scan for a (tenant, domain name). Backs the recency guard that
// dedupes discovered scans. Keyed on (tenant_id, domain_name), not domain_id,
// so it survives a domain delete/re-add.
func (q *Queries) ScansGetRecentByTenantDomainName(ctx context.Context, arg ScansGetRecentByTenantDomainNameParams) (Scans, error) {
	row := q.db.QueryRow(ctx, scansGetRecentByTenantDomainName, arg.TenantID, arg.DomainName)
	var i Scans
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.TenantID,
		&i.DomainID,
		&i.DomainUid,
		&i.DomainName,
		&i.ParentScanID,
		&i.Source,
		&i.StartedAt,
	)
	return i, err
}

const scansListByParent = `-- name: ScansListByParent :many
SELECT id, uid, tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source, started_at
FROM scans
WHERE parent_scan_id = $1
ORDER BY started_at DESC
`

// Child scans of an apex scan (lineage). Lets the timeline group discovered
// child scans under the scan that found them.
func (q *Queries) ScansListByParent(ctx context.Context, parentScanID pgtype.Int8) ([]Scans, error) {
	rows, err := q.db.Query(ctx, scansListByParent, parentScanID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scans{}
	for rows.Next() {
		var i Scans
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ParentScanID,
			&i.Source,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scansListByTenantDomainName = `-- name: ScansListByTenantDomainName :many
SELECT id, uid, tenant_id, domain_id, domain_uid, domain_name, parent_scan_id, source, started_at
FROM scans
WHERE tenant_id = $1
  AND domain_name = $2
ORDER BY started_at DESC
`

type ScansListByTenantDomainNameParams struct {
	TenantID   int32  `json:"tenant_id"`
	DomainName string `json:"domain_name"`
}

// All scans for a (tenant, domain name), newest first.
func (q *Queries) ScansListByTenantDomainName(ctx context.Context, arg ScansListByTenantDomainNameParams) ([]Scans, error) {
	rows, err := q.db.Query(ctx, scansListByTenantDomainName, arg.TenantID, arg.DomainName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Scans{}
	for rows.Next() {
		var i Scans
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.TenantID,
			&i.DomainID,
			&i.DomainUid,
			&i.DomainName,
			&i.ParentScanID,
			&i.Source,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
