// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const sessionCreate = `-- name: SessionCreate :one
INSERT INTO sessions (user_id, tenant_id, token_hash, expires_at, user_agent, ip)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING uid, expires_at, created_at, last_used_at
`

type SessionCreateParams struct {
	UserID    int32              `json:"user_id"`
	TenantID  int32              `json:"tenant_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
	Ip        pgtype.Text        `json:"ip"`
}

type SessionCreateRow struct {
	Uid        string             `json:"uid"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

func (q *Queries) SessionCreate(ctx context.Context, arg SessionCreateParams) (SessionCreateRow, error) {
	row := q.db.QueryRow(ctx, sessionCreate,
		arg.UserID,
		arg.TenantID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i SessionCreateRow
	err := row.Scan(
		&i.Uid,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const sessionResolve = `-- name: SessionResolve :one
SELECT s.user_id,
       s.tenant_id,
       s.token_hash,
       s.expires_at,
       s.last_used_at,
       u.email    AS user_email,
       u.role     AS user_role
FROM sessions s
         JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > NOW()
`

type SessionResolveRow struct {
	UserID     int32              `json:"user_id"`
	TenantID   int32              `json:"tenant_id"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	UserEmail  string             `json:"user_email"`
	UserRole   UserRole           `json:"user_role"`
}

// Returns only live sessions (expires_at > NOW()); expired sessions are treated
// as not-found by callers.
func (q *Queries) SessionResolve(ctx context.Context, tokenHash string) (SessionResolveRow, error) {
	row := q.db.QueryRow(ctx, sessionResolve, tokenHash)
	var i SessionResolveRow
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.UserEmail,
		&i.UserRole,
	)
	return i, err
}

const sessionRevoke = `-- name: SessionRevoke :exec
DELETE
FROM sessions
WHERE token_hash = $1
`

func (q *Queries) SessionRevoke(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, sessionRevoke, tokenHash)
	return err
}

const sessionRevokeAllForUser = `-- name: SessionRevokeAllForUser :exec
DELETE
FROM sessions
WHERE user_id = $1
`

// Invalidates every session for a user; called after a password reset so a
// forgotten/compromised credential cannot survive on an existing session.
func (q *Queries) SessionRevokeAllForUser(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, sessionRevokeAllForUser, userID)
	return err
}

const sessionTouch = `-- name: SessionTouch :exec
UPDATE sessions
SET last_used_at = NOW()
WHERE token_hash = $1
`

func (q *Queries) SessionTouch(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, sessionTouch, tokenHash)
	return err
}
