// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_stats.sql

package store

import (
	"context"
)

const tenantStatsGet = `-- name: TenantStatsGet :one
SELECT tenant_id, record_total, critical_count, warning_count, updated_at
FROM tenant_stats
WHERE tenant_id = $1
`

// Read a tenant's cached stat strip. Returns no row when the refresh job has not
// yet run for this tenant; callers fall back to placeholders.
func (q *Queries) TenantStatsGet(ctx context.Context, tenantID int32) (TenantStats, error) {
	row := q.db.QueryRow(ctx, tenantStatsGet, tenantID)
	var i TenantStats
	err := row.Scan(
		&i.TenantID,
		&i.RecordTotal,
		&i.CriticalCount,
		&i.WarningCount,
		&i.UpdatedAt,
	)
	return i, err
}

const tenantStatsUpsert = `-- name: TenantStatsUpsert :exec
INSERT INTO tenant_stats (tenant_id, record_total, critical_count, warning_count, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (tenant_id) DO UPDATE
    SET record_total   = EXCLUDED.record_total,
        critical_count = EXCLUDED.critical_count,
        warning_count  = EXCLUDED.warning_count,
        updated_at     = now()
`

type TenantStatsUpsertParams struct {
	TenantID      int32 `json:"tenant_id"`
	RecordTotal   int64 `json:"record_total"`
	CriticalCount int32 `json:"critical_count"`
	WarningCount  int32 `json:"warning_count"`
}

// Cache the periodic-refresh rollups for a tenant. ON CONFLICT keeps a single
// row per tenant and stamps updated_at on every refresh.
func (q *Queries) TenantStatsUpsert(ctx context.Context, arg TenantStatsUpsertParams) error {
	_, err := q.db.Exec(ctx, tenantStatsUpsert,
		arg.TenantID,
		arg.RecordTotal,
		arg.CriticalCount,
		arg.WarningCount,
	)
	return err
}
