// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_settings.sql

package store

import (
	"context"
)

const tenantSettingsGet = `-- name: TenantSettingsGet :one
SELECT tenant_id, default_scan_frequency, created_at, updated_at
FROM tenant_settings
WHERE tenant_id = $1
`

// Read a tenant's scan settings. Existing tenants were backfilled with a row; a
// brand-new tenant has none until first write, so callers treat pgx.ErrNoRows as
// "use the system default" rather than an error.
func (q *Queries) TenantSettingsGet(ctx context.Context, tenantID int32) (TenantSettings, error) {
	row := q.db.QueryRow(ctx, tenantSettingsGet, tenantID)
	var i TenantSettings
	err := row.Scan(
		&i.TenantID,
		&i.DefaultScanFrequency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const tenantSettingsUpsert = `-- name: TenantSettingsUpsert :one
INSERT INTO tenant_settings (tenant_id, default_scan_frequency)
VALUES ($1, $2)
ON CONFLICT (tenant_id)
    DO UPDATE SET default_scan_frequency = EXCLUDED.default_scan_frequency,
                  updated_at             = now()
RETURNING tenant_id, default_scan_frequency, created_at, updated_at
`

type TenantSettingsUpsertParams struct {
	TenantID             int32         `json:"tenant_id"`
	DefaultScanFrequency ScanFrequency `json:"default_scan_frequency"`
}

// Set a tenant's default scan frequency, creating the row on first write. One row
// per tenant; updated_at is refreshed by the trigger on UPDATE and stamped here on
// INSERT.
func (q *Queries) TenantSettingsUpsert(ctx context.Context, arg TenantSettingsUpsertParams) (TenantSettings, error) {
	row := q.db.QueryRow(ctx, tenantSettingsUpsert, arg.TenantID, arg.DefaultScanFrequency)
	var i TenantSettings
	err := row.Scan(
		&i.TenantID,
		&i.DefaultScanFrequency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
